standard_file_format = {
    "Portfolio": {
        "Extends Maturity Date": "object",
        "Initial Unrestricted Cash (Local Currency)": "Number",
        "Initial Annualized Recurring Revenue": "object",
        "Initial Liquidity": "object",
        "Interest Paid (Mthly, Qtrly)": "object",
        "Current Gross Total Debt (Local Currency)": "Number",
        "Maturity Date": "datetime64[ns]",
        "Origination Date": "datetime64[ns]",
        "Relevent Test Period": "datetime64[ns]",
        "Revolver": "object",
        "Current Unrestricted Cash (Local Currency)": "Number",
        "Borrower Facility Commitment": "Number",
        "Loan Type": "object",
        "Spread": "Number",
        "Eligible Loan Attestation": "object",
        "Upfront Approval Rights": "object",
        "Amends Definitions (Permitted Lien/Indebtedness)": "object",
        "Borrower Outstanding Principal Balance": "Number",
        "Current Liquidity": "object",
        "Exercise Rights and Remedies": "object",
        "Reduces/Waives Principal": "object",
        "Borrower": "object",
        "Reduces/Waives Interest": "object",
        "Initial Gross Total Debt (Local Currency)": "Number",
        "S&P Rating": "object",
        "DDTL": "object",
        "Subordinates Loan(s)": "object",
        "Releases Collateral/Lien": "object",
        "Waives or Extends Due Date of Financial Reports": "object",
        "Initial Gross Senior Debt (Local Currency)": "Number",
        "Finanicals Since Received?": "object",
        "Adjusted TTM EBITDA": "Number",
        "Current Gross Senior Debt (Local Currency)": "Number",
        "Amends Covenants": "object",
        "Date of TTM Financials": "datetime64[ns]",
        "RCF Outstanding Amount": "Number",
        "Acquisition Date": "datetime64[ns]",
        "Add-Backs": "Number",
        "RCF Update Date": "datetime64[ns]",
        "RCF Exposure Type": "object",
        "Current Cash Interest Expense": "Number",
        "Insolvency Event": "object",
        "Moody's Rating": "object",
        "Rated B- or Better": "object",
        "Paid Less than Qtrly": "object",
        "Obligor Payment Default": "object",
        "RCF Commitment Amount": "Number",
        "Approved Currency": "object",
        "Reporting Failure Event": "object",
        "Two Market Quotes": "object",
        "Acquisition Price": "Number",
        "Approved Industry": "object",
        "Initial TTM Adjusted EBITDA": "Number",
        "Approved Country": "object",
        "Is Fixed Rate": "object",
        "Cov-Lite": "object",
        "Initial Cash Interest Expense": "Number",
        "Annualized Recurring Revenue": "object",
        "DIP Loan": "object",
        "Admin Agent Approval (RCF)": "object",
        "Admin Agent Add-Back Discretion": "object",
        "Admin Agent Approved Add-Backs": "Number",
        "Date of Financial Delivery VAE": "datetime64[ns]",
        "Date Financials Provided to Ally": "datetime64[ns]",
    },
    "VAE": {
        "Obligor": "object",
        "Event Type": "object",
        "Material Modification": "object",
        "Date of VAE Decision": "datetime64[ns]",
        "Date of Financials": "datetime64[ns]",
        "TTM EBITDA": "Number",
        "Senior Debt": "Number",
        "Total Debt": "Number",
        "Unrestricted Cash": "Number",
        "Interest Coverage": "Number",
        "Recurring Revenue": "object",
        "Liquidity": "object",
        "Assigned Value": "Number"
    }
}