std_file_format = {
    "Loan List": {
        "Obligor Name": "object",
        "Security Name": "object",
        "Purchase Date (Date Loan contributed to the facility)": "Number",
        "Total Commitment (Issue Currency)": "Number",
        "Outstanding Principal Balance (Issue Currency)": "Number",
        "Defaulted Collateral Loan / Material Mod (Y/N)": "object",
        "Date of Default": "datetime64[ns]",
        "Credit Improved Loan (Y/N)": "object",
        "Purchase Price": "Number",
        "Market Value": "Number",
        "Stretch Senior Loan (Y/N)": "object",
        "Lien Type (First Lien / Split First Lien / Split Lien / Second Lien / Tier 1 Split Lien / Tier 2 Split Lien)": "object",  # Lien Type (First Lien / Split First Lien / Split Lien / Second Lien) now changed to Lien Type (First Lien / Split First Lien / Split Lien / Second Lien / Tier 1 Split Lien / Tier 2 Split Lien)
        "Loan Type (Term / Delayed Draw / Revolver)": "object",
        "Current Moody's Rating": "object",
        "Current S&P Rating": "object",
        "Initial Fixed Charge Coverage Ratio": "Number",
        "Current Fixed Charge Coverage Ratio": "Number",
        "Current Interest Coverage Ratio": "Number",
        "Debt to Capitalization Ratio": "Number",
        "Initial Senior Debt/EBITDA": "Number",
        "Initial Total Debt/EBITDA": "Number",
        "Current Senior Debt/EBITDA": "Number",
        "Current Total Debt/EBITDA": "Number",
        "Initial TTM EBITDA": "Number",
        "Current TTM EBITDA": "Number",
        "Current As of Date For Leverage and EBITDA": "datetime64[ns]",
        "Maturity Date": "datetime64[ns]",
        "Fixed Rate (Y/N)": "object",
        "Coupon incl. PIK and PIK'able (if Fixed)": "Number",  # Coupon (if Fixed) now changed to -> Coupon incl. PIK and PIK'able (if Fixed)
        "Floor Obligation (Y/N)": "object",
        "Floor": "Number",
        "Spread incl. PIK and PIK'able": "Number",  # Spread is now changed to -> Spread incl. PIK and PIK'able
        "Base Rate": "Number",
        "For Revolvers/Delayed Draw, commitment or other unused fee": "Number",
        "PIK / PIK'able For Floating Rate Loans": "Number",  # PIK Floating Rate now changed to -> PIK / PIK'able For Floating Rate Loans
        "PIK / PIK'able For Fixed Rate Loans": "Number",  # PIK Fixed Rate now changed to -> PIK / PIK'able For Fixed Rate Loans
        "Interest Paid": "object",
        "Obligor Industry": "object",
        "Currency (USD / CAD / AUD / EUR)": "object",
        "Obligor Country": "object",
        "DIP Loan (Y/N)": "object",
        # "Partial PIK Loan (Y/N)": "object",
        "Warrants to Purchase Equity (Y/N)": "object",
        "LBO Loan (Y/N)": "object",
        "Parti-cipation (Y/N)": "object",
        "Convertible to Equity (Y/N)": "object",
        "Equity Security (Y/N)": "object",
        "At Acquisition - Subject to offer or called for redemption (Y/N)": "object",
        "Margin Stock (Y/N)": "object",
        "Subject to withholding tax (Y/N)": "object",
        "At Acquisition - Defaulted Collateral Loan": "object",
        # "Non-Cash PIK (Y/N)": "object",
        "Zero Coupon Obligation (Y/N)": "object",
        "Covenant Lite (Y/N)": "object",
        "Eligible Covenant Lite (Y/N)": "object",
        "Structured Finance Obligation, finance lease or chattel paper (Y/N)": "object",
        "Material Non-Credit Related Risk (Y/N)": "object",
        "Primarily Secured by Real Estate, Construction Loan or Project Finance Loan (Y/N)": "object",
        "Interest Only Security (Y/N)": "object",
        "Satisfies all Other Eligibility Criteria (Y/N)": "object",
        "Excess Concentration Amount (HARD CODE on Last Day of Reinvestment Period)": "Number",
    },
    "Inputs": {"INPUTS": "object", "Values": "object"},
    "Exchange Rates": {"Currency": "object", "Exchange Rate": "Number"},
    "Haircut": {
        "20% Conc. Limit": "object",
        "Level 1 - 10% Haircut": "object",
        "Level 2 - 20% Haircut": "object",
        "Level 3 - 35% Haircut": "object",
        "Level 4 - Max Eligibility - 50% Haircut": "object",
    },
    "Industry": {"Industry No": "Number", "Industry": "object"},
    "Cash Balance Projections": {
        "Currency": "object",
        "Exchange Rates": "Number",
        "Cash - Current & PreBorrowing": "Number",
        "Borrowing": "Number",
        "Additional Expences 1": "Number",
        "Additional Expences 2": "Number",
        "Additional Expences 3": "Number",
    },
    "Credit Balance Projection": {
        "Currency": "object",
        "Current Credit Facility Balance": "Number",
    },
}
