export const PCOFAddAssetData = [
    {
      "Investment Name": "Simplicity Group First Lien",
      "Issuer": "Simplicity Group",
      "Investment Investment Type": "First Lien",
      "Investment Industry": "Financial Services",
      "Investment Closing Date": "2023-04-05",
      "Investment Maturity": "2026-12-02",
      "Investment Par": 3603603.6,
      "Investment Cost": 3532933.08,
      "Investment External Valuation": 3531531.528,
      "Investment Internal Valuation": NaN,
      "Rates Fixed Coupon": NaN,
      "Rates Floating Cash Spread": 0.0625,
      "Rates Current LIBOR/Floor": 0.0507063,
      "Rates PIK": NaN,
      "Rates Fixed / Floating": "Floating",
      "Classifications Quoted / Unquoted": "Unquoted",
      "Classifications Warehouse Asset": "No",
      "Classifications Warehouse Asset Inclusion Date": NaN,
      "Classifications Warehouse Asset Expected Rating": NaN,
      "Classifications Approved Foreign Jurisdiction": NaN,
      "Classifications LTV Transaction": "No",
      "Classifications Noteless Assigned Loan": "No",
      "Classifications Undelivered Note": "No",
      "Classifications Structured Finance Obligation": "No",
      "Classifications Third Party Finance Company": "No",
      "Classifications Affiliate Investment": "No",
      "Classifications Defaulted / Restructured": "No",
      "Financials LTM Revenue ($MMs)": 489,
      "Financials LTM EBITDA ($MMs)": 103.2,
      "Leverage Revolver Commitment": 23.5,
      "Leverage Total Enterprise Value": 774.7,
      "Leverage Total Leverage": 5.13,
      "Leverage PCOF IV Leverage": 5.13,
      "Leverage Attachment Point": NaN,
      "Leverage Total Capitalization": NaN,
      "Leverage LTV Thru PCOF IV": 0.61,
      "Final Eligibility Override": NaN,
      "Final Comment": NaN,
      "Concentration Adjustment": NaN,
      "Concentration Comment": NaN,
      "Borrowing Base Other Adjustment": NaN,
      "Borrowing Base Industry Concentration": NaN,
      "Borrowing Base Comment": NaN,
      "Is Eligible Issuer": "Yes"
    },
    {
      "Investment Name": "Simplicity Group DDTL",
      "Issuer": "Simplicity Group",
      "Investment Investment Type": "First Lien",
      "Investment Industry": "Financial Services",
      "Investment Closing Date": "2023-04-05",
      "Investment Maturity": "2026-12-02",
      "Investment Par": 889639.64,
      "Investment Cost": 0.0,
      "Investment External Valuation": -889639.64,
      "Investment Internal Valuation": NaN,
      "Rates Fixed Coupon": NaN,
      "Rates Floating Cash Spread": 0.0625,
      "Rates Current LIBOR/Floor": 0.0507063,
      "Rates PIK": NaN,
      "Rates Fixed / Floating": "Floating",
      "Classifications Quoted / Unquoted": "Unquoted",
      "Classifications Warehouse Asset": "No",
      "Classifications Warehouse Asset Inclusion Date": NaN,
      "Classifications Warehouse Asset Expected Rating": NaN,
      "Classifications Approved Foreign Jurisdiction": NaN,
      "Classifications LTV Transaction": "No",
      "Classifications Noteless Assigned Loan": "No",
      "Classifications Undelivered Note": "No",
      "Classifications Structured Finance Obligation": "No",
      "Classifications Third Party Finance Company": "No",
      "Classifications Affiliate Investment": "No",
      "Classifications Defaulted / Restructured": "No",
      "Financials LTM Revenue ($MMs)": 489,
      "Financials LTM EBITDA ($MMs)": 103.2,
      "Leverage Revolver Commitment": 23.5,
      "Leverage Total Enterprise Value": 774.7,
      "Leverage Total Leverage": 5.13,
      "Leverage PCOF IV Leverage": 5.13,
      "Leverage Attachment Point": NaN,
      "Leverage Total Capitalization": NaN,
      "Leverage LTV Thru PCOF IV": 0.61,
      "Final Eligibility Override": NaN,
      "Final Comment": NaN,
      "Concentration Adjustment": NaN,
      "Concentration Comment": NaN,
      "Borrowing Base Other Adjustment": NaN,
      "Borrowing Base Industry Concentration": NaN,
      "Borrowing Base Comment": NaN,
      "Is Eligible Issuer": "Yes"
    },
    {
      "Investment Name": "Simplicity Group Revolver",
      "Issuer": "Simplicity Group",
      "Investment Investment Type": "First Lien",
      "Investment Industry": "Financial Services",
      "Investment Closing Date": "2023-04-05",
      "Investment Maturity": "2026-12-02",
      "Investment Par": 236486.49,
      "Investment Cost": 0.0,
      "Investment External Valuation": -236486.49,
      "Investment Internal Valuation": NaN,
      "Rates Fixed Coupon": NaN,
      "Rates Floating Cash Spread": 0.0625,
      "Rates Current LIBOR/Floor": 0.0507063,
      "Rates PIK": NaN,
      "Rates Fixed / Floating": "Floating",
      "Classifications Quoted / Unquoted": "Unquoted",
      "Classifications Warehouse Asset": "No",
      "Classifications Warehouse Asset Inclusion Date": NaN,
      "Classifications Warehouse Asset Expected Rating": NaN,
      "Classifications Approved Foreign Jurisdiction": NaN,
      "Classifications LTV Transaction": "No",
      "Classifications Noteless Assigned Loan": "No",
      "Classifications Undelivered Note": "No",
      "Classifications Structured Finance Obligation": "No",
      "Classifications Third Party Finance Company": "No",
      "Classifications Affiliate Investment": "No",
      "Classifications Defaulted / Restructured": "No",
      "Financials LTM Revenue ($MMs)": 489,
      "Financials LTM EBITDA ($MMs)": 103.2,
      "Leverage Revolver Commitment": 23.5,
      "Leverage Total Enterprise Value": 774.7,
      "Leverage Total Leverage": 5.13,
      "Leverage PCOF IV Leverage": 5.13,
      "Leverage Attachment Point": NaN,
      "Leverage Total Capitalization": NaN,
      "Leverage LTV Thru PCOF IV": 0.61,
      "Final Eligibility Override": NaN,
      "Final Comment": NaN,
      "Concentration Adjustment": NaN,
      "Concentration Comment": NaN,
      "Borrowing Base Other Adjustment": NaN,
      "Borrowing Base Industry Concentration": NaN,
      "Borrowing Base Comment": NaN,
      "Is Eligible Issuer": "Yes"
    }
  ];