INSERT INTO column_metadata_master (
	fund_id , sheet_id , company_id , column_name , column_lookup , description , data_type , unit , "sequence" , is_raw_data_input , is_mandatory , is_required , created_by , column_number 
) VALUES 
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'Borrower', 'borrower', 'Borrower', 'string', '', 1, true, true, true, 1, 'A'),
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'Borrower Facility Commitment', 'borrower_facility_commitment', 'Borrower Facility Commitment', 'float', '', 2, true, true, true, 1, 'B'),
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'Borrower Outstanding Principal Balance', 'borrower_outstanding_principal_balance', 'Borrower Outstanding Principal Balance', 'float', '', 3, true, true, true, 1, 'C'),
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'Initial Gross Senior Debt (Local Currency)', 'initial_gross_senior_debt', 'Initial Gross Senior Debt (Local Currency)', 'float', '', 4, true, true, true, 1, 'D'),
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'Initial Gross Total Debt (Local Currency)', 'initial_total_senior_debt', 'Initial Total Senior Debt (Local Currency)', 'float', '', 5, true, true, true, 1, 'E'),
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'Current Unrestricted Cash (Local Currency)', 'current_unrestricted_cash', 'Current Unrestricted Cash (Local Currency)', 'float', '', 6, true, true, true, 1, 'F'),
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'Interest Paid (Mthly, Qtrly)', 'interest_paid', 'Interest Paid (Mthly, Qtrly)', 'string', '', 7, true, true, true, 1, 'G'),
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'Current Gross Senior Debt (Local Currency)', 'current_gross_senior_debt', 'Current Gross Senior Debt (Local Currency)', 'float', '', 8, true, true, true, 1, 'H'),
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'Paid Less than Qtrly', 'paid_less_than_qtrly', 'Paid Less than Qtrly', 'string', '', 9, true, true, true, 1, 'I'),
	(3, (select smm_id from sheet_metadata_master where lookup = 'portfolio'), 1, 'S&P Rating', 'sp_rating', 'S&P Rating', 'string', '', 10, true, true, true, 1, 'J'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Moody''s Rating', 'moodys_rating', 'Moody''s Rating', 'string', '', 11, true, true, true, 1, 'K'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Rated B- or Better', 'rated_b_or_better', 'Rated B- or Better', 'string', '', 12, true, true, true, 1, 'L'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Adjusted TTM EBITDA', 'adjusted_ttm_ebitda', 'Adjusted TTM EBITDA', 'string', '', 13, true, true, true, 1, 'M'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Two Market Quotes', 'two_market_quotes', 'Two Market Quotes', 'string', '', 14, true, true, true, 1, 'N'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Date of TTM Financials', 'date_of_ttm_financials', 'Date of TTM Financials', 'datetime', '', 15, true, true, true, 1, 'O'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Initial TTM Adjusted EBITDA', 'initial_ttm_adjusted_ebitda', 'Initial TTM Adjusted EBITDA', 'float', '', 16, true, true, true, 1, 'P'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Add-Backs', 'add_backs', 'Add-Backs', 'float', '', 17, true, true, true, 1, 'Q'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Obligor Payment Default', 'obligor_payment_default', 'Obligor Payment Default', 'string', '', 18, true, true, true, 1, 'R'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Exercise Rights and Remedies', 'exercise_rights_and_remedies', 'Exercise Rights and Remedies', 'string', '', 19, true, true, true, 1, 'S'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Reduces/Waives Principal', 'reduces_waives_principal', 'Reduces/Waives Principal', 'string', '', 20, true, true, true, 1, 'T'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Initial Unrestricted Cash (Local Currency)', 'initial_unrestricted_cash', 'Initial Unrestricted Cash (Local Currency)', 'float', '', 21, true, true, true, 1, 'U'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'DDTL', 'ddtl', 'DDTL', 'string', '', 22, true, true, true, 1, 'V'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Relevent Test Period', 'relevent_test_period', 'Relevent Test Period', 'datetime', '', 23, true, true, true, 1, 'W'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Initial Annualized Recurring Revenue', 'initial_annualized_recurring_revenue', 'Initial Annualized Recurring Revenue', 'string', '', 24, true, true, true, 1, 'X'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Annualized Recurring Revenue', 'annualized_recurring_revenue', 'Annualized Recurring Revenue', 'string', '', 25, true, true, true, 1, 'Y'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Initial Liquidity', 'initial_liquidity', 'Initial Liquidity', 'string', '', 26, true, true, true, 1, 'Z'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Current Liquidity', 'current_liquidity', 'Current Liquidity', 'string', '', 27, true, true, true, 1, 'AA'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Initial Cash Interest Expense', 'initial_cash_interest_expense', 'Initial Cash Interest Expense', 'string', '', 28, true, true, true, 1, 'AB'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Current Cash Interest Expense', 'current_cash_interest_expense', 'Current Cash Interest Expense', 'string', '', 29, true, true, true, 1, 'AC'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Amends Definitions (Permitted Lien/Indebtedness)', 'amends_definitions', 'Amends Definitions (Permitted Lien/Indebtedness)', 'string', '', 30, true, true, true, 1, 'AD'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Waives or Extends Due Date of Financial Reports', 'waives_or_extends_due_date_of_financial_reports', 'Waives or Extends Due Date of Financial Reports', 'string', '', 31, true, true, true, 1, 'AE'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Financials Since Received?', 'financials_since_received', 'Financials Since Received?', 'string', '', 32, true, true, true, 1, 'AF'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'RCF Outstanding Amount', 'rcf_outstanding_amount', 'RCF Outstanding Amount', 'string', '', 33, true, true, true, 1, 'AG'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'RCF Update Date', 'rcf_update_date', 'RCF Update Date', 'datetime', '', 34, true, true, true, 1, 'AH'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Current Gross Total Debt (Local Currency)', 'current_gross_total_debt', 'Current Gross Total Debt (Local Currency)', 'float', '', 35, true, true, true, 1, 'AI'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Upfront Approval Rights', 'upfront_approval_rights', 'Upfront Approval Rights', 'string', '', 36, true, true, true, 1, 'AJ'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Eligible Loan Attestation', 'eligible_loan_attestation', 'Eligible Loan Attestation', 'string', '', 37, true, true, true, 1, 'AK'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Cov-Lite', 'cov_lite', 'Cov-Lite', 'string', '', 38, true, true, true, 1, 'AL'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Spread', 'spread', 'Spread', 'float', 'percent', 39, true, true, true, 1, 'AM'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'DIP Loan', 'dip_loan', 'DIP Loan', 'string', '', 40, true, true, true, 1, 'AN'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Approved Country', 'approved_country', 'Approved Country', 'string', '', 41, true, true, true, 1, 'AO'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Approved Currency', 'approved_currency', 'Approved Currency', 'string', '', 42, true, true, true, 1, 'AP'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Approved Industry', 'approved_industry', 'Approved Industry', 'string', '', 43, true, true, true, 1, 'AQ'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Is Fixed Rate', 'is_fixed_rate', 'Is Fixed Rate', 'string', '', 44, true, true, true, 1, 'AR'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Subordinates Loan(s)', 'subordinates_loans', 'Subordinates Loan(s)', 'string', '', 45, true, true, true, 1, 'AS'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Releases Collateral/Lien', 'releases_collateral_lien', 'Releases Collateral/Lien', 'string', '', 46, true, true, true, 1, 'AT'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Amends Covenants', 'amends_covenants', 'Amends Covenants', 'string', '', 47, true, true, true, 1, 'AU'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Reporting Failure Event', 'reporting_failure_event', 'Reporting Failure Event', 'string', '', 48, true, true, true, 1, 'AV'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Insolvency Event', 'insolvency_event', 'Insolvency Event', 'string', '', 49, true, true, true, 1, 'AW'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Loan Type', 'loan_type', 'Loan Type', 'string', '', 50, true, true, true, 1, 'AX'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'RCF Exposure Type', 'rcf_exposure_type', 'RCF Exposure Type', 'string', '', 51, true, true, true, 1, 'AY'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'RCF Commitment Amount', 'rcf_commitment_amount', 'RCF Commitment Amount', 'float', '', 52, true, true, true, 1, 'AZ'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Acquisition Price', 'acquisition_price', 'Acquisition Price', 'float', 'percent', 53, true, true, true, 1, 'BA'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Origination Date', 'origination_date', 'Origination Date', 'datetime', '', 54, true, false, false, 1, 'BB'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Acquisition Date', 'acquisition_date', 'Acquisition Date', 'datetime', '', 55, true, false, false, 1, 'BC'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Maturity Date', 'maturity_date', 'Maturity Date', 'datetime', '', 56, true, true, true, 1, 'BD'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Revolver', 'revolver', 'Revolver', 'string', '', 57, true, true, true, 1, 'BE'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Extends Maturity Date', 'extends_maturity_date', 'Extends Maturity Date', 'string', '', 58, true, true, true, 1, 'BF'),
	(3, (SELECT smm_id FROM sheet_metadata_master WHERE lookup = 'portfolio'), 1, 'Reduces/Waives Interest', 'reduces_waives_interest', 'Reduces/Waives Interest', 'string', '', 59, true, true, true, 1, 'BG');


INSERT INTO column_metadata_master (
	fund_id , sheet_id , company_id , column_name , column_lookup , description , data_type , unit , "sequence" , is_raw_data_input , is_mandatory , is_required , created_by , column_number 
) VALUES 
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Issuer', 'issuer', 'Issuer', 'string', '', 1, true, true, true, 1, 'A'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Investment Name', 'investment_name', 'Investment Name', 'string', '', 2, true, true, true, 1, 'B'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Rates PIK', 'rates_pik', 'Rates PIK', 'float', 'percent', 3, true, true, true, 1, 'C'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Investment Cost', 'investment_cost', 'Investment Cost', 'float', '', 4, true, true, true, 1, 'D'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Investment External Valuation', 'investment_external_valuation', 'Investment External Valuation', 'float', '', 5, true, true, true, 1, 'E'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Investment Par', 'investment_par', 'Investment Par', 'float', '', 6, true, true, true, 1, 'F'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Investment Maturity', 'investment_maturity', 'Investment Maturity', 'datetime', '', 7, true, true, true, 1, 'G'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Leverage LTV Thru PCOF IV', 'leverage_ltv_thru_pcof_iv', 'Leverage LTV Thru PCOF IV', 'float', 'percent', 8, true, true, true, 1, 'H'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Quoted / Unquoted', 'classifications_quoted_unquoted', 'Classifications Quoted / Unquoted', 'string', '', 9, true, true, true, 1, 'I'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Warehouse Asset', 'classifications_warehouse_asset', 'Classifications Warehouse Asset', 'string', '', 10, true, true, true, 1, 'J'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Warehouse Asset Expected Rating', 'classifications_warehouse_asset_expected_rating', 'Classifications Warehouse Asset Expected Rating', 'string', '', 11, true, true, true, 1, 'K'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Approved Foreign Jurisdiction', 'classifications_approved_foreign_jurisdiction', 'Classifications Approved Foreign Jurisdiction', 'string', '', 12, true, true, true, 1, 'L'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications LTV Transaction', 'classifications_ltv_transaction', 'Classifications LTV Transaction', 'string', '', 13, true, true, true, 1, 'M'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Undelivered Note', 'classifications_undelivered_note', 'Classifications Undelivered Note', 'string', '', 14, true, true, true, 1, 'N'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Rates Fixed / Floating', 'rates_fixed_floating', 'Rates Fixed / Floating', 'string', '', 15, true, true, true, 1, 'O'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Rates Floating Cash Spread', 'rates_floating_cash_spread', 'Rates Floating Cash Spread', 'float', 'percent', 16, true, true, true, 1, 'P'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Investment Industry', 'investment_industry', 'Investment Industry', 'string', '', 17, true, true, true, 1, 'Q'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Rates Current LIBOR/Floor', 'rates_current_libor_floor', 'Rates Current LIBOR/Floor', 'float', 'percent', 18, true, true, true, 1, 'R'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Rates Fixed Coupon', 'rates_fixed_coupon', 'Rates Fixed Coupon', 'float', 'string', 19, true, true, true, 1, 'S'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Concentration Adjustment', 'concentration_adjustment', 'Concentration Adjustment', 'string', '', 20, true, true, true, 1, 'T'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Concentration Comment', 'concentration_comment', 'Concentration Comment', 'string', '', 21, true, true, true, 1, 'U'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Borrowing Base Other Adjustment', 'borrowing_base_other_adjustment', 'Borrowing Base Other Adjustment', 'string', '', 22, true, true, true, 1, 'V'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Borrowing Base Industry Concentration', 'borrowing_base_industry_concentration', 'Borrowing Base Industry Concentration', 'string', '', 23, true, true, true, 1, 'W'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Leverage Total Enterprise Value', 'leverage_total_enterprise_value', 'Leverage Total Enterprise Value', 'float', '', 24, true, true, true, 1, 'X'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Investment Investment Type', 'investment_investment_type', 'Investment Investment Type', 'string', '', 25, true, true, true, 1, 'Y'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Leverage Total Leverage', 'leverage_total_leverage', 'Leverage Total Leverage', 'float', '', 26, true, true, true, 1, 'Z'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Financials LTM Revenue ($MMs)', 'financials_ltm_revenue', 'Financials LTM Revenue ($MMs)', 'float', '', 27, true, true, true, 1, 'AA'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Investment Internal Valuation', 'investment_internal_valuation', 'Investment Internal Valuation', 'string', '', 28, true, true, true, 1, 'AB'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Warehouse Asset Inclusion Date', 'classifications_warehouse_asset_inclusion_date', 'Classifications Warehouse Asset Inclusion Date', 'string', '', 29, true, true, true, 1, 'AC'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Leverage Revolver Commitment', 'leverage_revolver_commitment', 'Leverage Revolver Commitment', 'string', '', 30, true, true, true, 1, 'AD'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Leverage Attachment Point', 'leverage_attachment_point', 'Leverage Attachment Point', 'string', '', 31, true, true, true, 1, 'AE'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Final Eligibility Override', 'final_eligibility_override', 'Final Eligibility Override', 'string', '', 32, true, true, true, 1, 'AF'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Final Comment', 'final_comment', 'Final Comment', 'string', '', 33, true, true, true, 1, 'AG'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Structured Finance Obligation', 'classifications_structured_finance_obligation', 'Classifications Structured Finance Obligation', 'string', '', 34, true, true, true, 1, 'AH'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Third Party Finance Company', 'classifications_third_party_finance_company', 'Classifications Third Party Finance Company', 'string', '', 35, true, true, true, 1, 'AI'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Affiliate Investment', 'classifications_affiliate_investment', 'Classifications Affiliate Investment', 'string', '', 36, true, true, true, 1, 'AJ'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Borrowing Base Comment', 'borrowing_base_comment', 'Borrowing Base Comment', 'string', '', 37, true, true, true, 1, 'AK'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Defaulted / Restructured', 'classifications_defaulted_restructured', 'Classifications Defaulted / Restructured', 'string', '', 38, true, true, true, 1, 'AL'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Is Eligible Issuer', 'is_eligible_issuer', 'Is Eligible Issuer', 'string', '', 39, true, true, true, 1, 'AM'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Leverage Total Capitalization', 'leverage_total_capitalization', 'Leverage Total Capitalization', 'string', '', 40, true, true, true, 1, 'AN'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Investment Closing Date', 'investment_closing_date', 'Investment Closing Date', 'datetime', '', 41, true, true, true, 1, 'AO)'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Classifications Noteless Assigned Loan', 'classifications_noteless_assigned_loan', 'Classifications Noteless Assigned Loan', 'string', '', 42, true, true, true, 1, 'AP'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Financials LTM EBITDA ($MMs)', 'financials_ltm_ebitda', 'Financials LTM EBITDA ($MMs)', 'string', '', 43, true, true, true, 1, 'AQ'),
	(1, (select smm_id from sheet_metadata_master where lookup = 'pl_bb_build'), 1, 'Leverage PCOF IV Leverage', 'leverage_pcof_iv_leverage', 'Leverage PCOF IV Leverage', 'string', '', 44, true, true, true, 1, 'AR');
	
	
INSERT INTO column_metadata_master (
  fund_id , sheet_id , company_id , column_name , column_lookup , description , data_type , unit , "sequence" , is_raw_data_input , is_mandatory , is_required , created_by , column_number 
) VALUES 
  	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Obligor Name', 'obligor_name', 'Obligor Name', 'string', '', 1, true, true, true, 1, 'A'),
  	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Total Commitment (Issue Currency)', 'total_commitment', 'Total Commitment (Issue Currency)', 'float', '', 2, true, true, true, 1, 'B'),
  	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Security Name', 'security_name', 'Security Name', 'string', '', 3, true, true, true, 1, 'C'),
	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Outstanding Principal Balance (Issue Currency)', 'outstanding_principal_balance', 'Outstanding Principal Balance (Issue Currency)', 'float', '', 4, true, true, true, 1, 'D'),
	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Convertible to Equity (Y/N)', 'convertible_to_equity', 'Convertible to Equity (Y/N)', 'string', '', 5, true, true, true, 1, 'E'),
	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Stretch Senior Loan (Y/N)', 'stretch_senior_loan', 'Stretch Senior Loan (Y/N)', 'string', '', 6, true, true, true, 1, 'F'),
	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'At Acquisition - Subject to offer or called for redemption (Y/N)', 'at_acquisition_subject_to_offer_or_called_for_redemption ', 'At Acquisition - Subject to offer or called for redemption (Y/N)', 'string', '', 7, true, true, true, 1, 'G'),
	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Primarily Secured by Real Estate, Construction Loan or Project Finance Loan (Y/N)', 'primarily_secured_by_real_estate_construction_loan_or_project_finance_loan ', 'Primarily Secured by Real Estate, Construction Loan or Project Finance Loan (Y/N)', 'string', '', 8, true, true, true, 1, 'H'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Structured Finance Obligation, finance lease or chattel paper (Y/N)', 'structured_finance_obligation_finance_lease_or_chattel_paper', 'Structured Finance Obligation, finance lease or chattel paper (Y/N)', 'string', '', 9, true, true, true, 1, 'I'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Interest Only Security (Y/N)', 'interest_only_security', 'Interest Only Security (Y/N)', 'string', '', 10, true, true, true, 1, 'J'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Satisfies all Other Eligibility Criteria (Y/N)', 'satisfies_all_other_eligibility_criteria', 'Satisfies all Other Eligibility Criteria (Y/N)', 'string', '', 11, true, true, true, 1, 'K'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Fixed Rate (Y/N)', 'fixed_rate', 'Fixed Rate (Y/N)', 'string', '', 12, true, true, true, 1, 'L'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Initial Fixed Charge Coverage Ratio', 'initial_fixed_charge_coverage_ratio', 'Initial Fixed Charge Coverage Ratio', 'float', '', 13, true, true, true, 1, 'M'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Lien Type (First Lien / Split First Lien / Split Lien / Second Lien / Tier 1 Split Lien / Tier 2 Split Lien)', 'lien_type', 'Lien Type (First Lien / Split First Lien / Split Lien / Second Lien / Tier 1 Split Lien / Tier 2 Split Lien)', 'string', '', 14, true, true, true, 1, 'N'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Defaulted Collateral Loan / Material Mod (Y/N)', 'defaulted_collateral_loan_material_mod', 'Defaulted Collateral Loan / Material Mod (Y/N)', 'string', '', 15, true, true, true, 1, 'O'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'LoanX ID', 'loanx_id', 'LoanX ID', 'string', '', 16, true, true, true, 1, 'P'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Date of Default', 'date_of_default', 'Date of Default', 'datetime', '', 17, true, false, false, 1, 'Q'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Market Value', 'market_value', 'Market Value', 'float', '', 18, true, true, true, 1, 'R'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Base Rate', 'base_rate', 'Base Rate', 'float', 'percent', 19, true, true, true, 1, 'S'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'PIK / PIK''able For Floating Rate Loans', 'pik_able_for_floating_rate_loans', 'PIK / PIK''able For Floating Rate Loans', 'float', 'percent', 20, true, true, true, 1, 'T'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'PIK / PIK''able For Fixed Rate Loans', 'pik_able_for_fixed_rate_loans', 'PIK / PIK''able For Fixed Rate Loans', 'float', 'percent', 21, true, true, true, 1, 'U'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Initial Senior Debt/EBITDA', 'initial_senior_debt_ebitda', 'Initial Senior Debt/EBITDA', 'float', '', 22, true, true, true, 1, 'V'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Current As of Date For Leverage and EBITDA', 'current_as_of_date_for_leverage_and_ebitda', 'Current As of Date For Leverage and EBITDA', 'datetime', '', 23, true, true, true, 1, 'W'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Purchase Price', 'purchase_price', 'Purchase Price', 'float', '', 24, true, true, true, 1, 'X'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Purchase Date (Date Loan contributed to the facility)', 'purchase_date', 'Purchase Date (Date Loan contributed to the facility)', 'string', '', 25, true, false, false, 1, 'Y'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Current Fixed Charge Coverage Ratio', 'current_fixed_charge_coverage_ratio', 'Current Fixed Charge Coverage Ratio', 'float', '', 26, true, true, true, 1, 'Z'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'DIP Loan (Y/N)', 'dip_loan', 'DIP Loan (Y/N)', 'string', '', 27, true, true, true, 1, 'AA'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'For Revolvers/Delayed Draw, commitment or other unused fee', 'for_revolvers_delayed_draw_commitment_or_other_unused_fee', 'For Revolvers/Delayed Draw, commitment or other unused fee', 'string', '', 28, true, true, true, 1, 'AB'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Current Interest Coverage Ratio', 'current_interest_coverage_ratio', 'Current Interest Coverage Ratio', 'float', '', 29, true, true, true, 1, 'AC'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Initial Total Debt/EBITDA', 'initial_total_debt_to_ebitda', 'Initial Total Debt/EBITDA', 'float', '', 30, true, true, true, 1, 'AD'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Current TTM EBITDA', 'current_ttm_ebitda', 'Current TTM EBITDA', 'float', '', 31, true, true, true, 1, 'AE'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Current Senior Debt/EBITDA', 'current_senior_debt_ebitda', 'Current Senior Debt/EBITDA', 'float', '', 32, true, true, true, 1, 'AF'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Covenant Lite (Y/N)', 'covenant_lite', 'Covenant Lite (Y/N)', 'string', '', 33, true, true, true, 1, 'AG'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Material Non-Credit Related Risk (Y/N)', 'material_non_credit_related_risk', 'Material Non-Credit Related Risk (Y/N)', 'string', '', 34, true, true, true, 1, 'AH'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'At Acquisition - Defaulted Collateral Loan', 'at_acquisition_defaulted_collateral_loan', 'At Acquisition - Defaulted Collateral Loan', 'string', '', 35, true, true, true, 1, 'AI'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Floor', 'floor', 'Floor', 'float', 'percent', 36, true, true, true, 1, 'AJ'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Spread incl. PIK and PIK''able', 'spread_incl_pik_and_pik_able', 'Spread incl. PIK and PIK''able', 'float', 'percent', 37, true, true, true, 1, 'AK'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Interest Paid', 'interest_paid', 'Interest Paid', 'string', '', 38, true, true, true, 1, 'AL'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Excess Concentration Amount (HARD CODE on Last Day of Reinvestment Period)', 'excess_concentration_amount', 'Excess Concentration Amount (HARD CODE on Last Day of Reinvestment Period)', 'string', '', 39, true, true, true, 1, 'AM'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Floor Obligation (Y/N)', 'floor_obligation', 'Floor Obligation (Y/N)', 'string', '', 40, true, true, true, 1, 'AN'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Current Total Debt/EBITDA', 'current_total_debt_ebitda', 'Current Total Debt/EBITDA', 'float', '', 41, true, true, true, 1, 'AO'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Obligor Industry', 'obligor_industry', 'Obligor Industry', 'string', '', 42, true, true, true, 1, 'AP'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Loan Type (Term / Delayed Draw / Revolver)', 'loan_type', 'Loan Type (Term / Delayed Draw / Revolver)', 'string', '', 43, true, true, true, 1, 'AQ'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Warrants to Purchase Equity (Y/N)', 'warrants_to_purchase_equity', 'Warrants to Purchase Equity (Y/N)', 'string', '', 44, true, true, true, 1, 'AR'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'LBO Loan (Y/N)', 'lbo_loan', 'LBO Loan (Y/N)', 'string', '', 45, true, true, true, 1, 'AS'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Parti-cipation (Y/N)', 'parti_cipation', 'Parti-cipation (Y/N)', 'string', '', 46, true, true, true, 1, 'AT'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Margin Stock (Y/N)', 'margin_stock', 'Margin Stock (Y/N)', 'string', '', 47, true, true, true, 1, 'AU'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Subject to withholding tax (Y/N)', 'subject_to_withholding_tax', 'Subject to withholding tax (Y/N)', 'string', '', 48, true, true, true, 1, 'AV'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Zero Coupon Obligation (Y/N)', 'zero_coupon_boligation', 'Zero Coupon Obligation (Y/N)', 'string', '', 49, true, true, true, 1, 'AW'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Coupon incl. PIK and PIK''able (if Fixed)', 'coupon_incl_pik_and_pik_able', 'Coupon incl. PIK and PIK''able (if Fixed)', 'float', 'percent', 50, true, true, true, 1, 'AX'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Currency (USD / CAD / AUD / EUR)', 'currency', 'Currency (USD / CAD / AUD / EUR)', 'string', '', 51, true, true, true, 1, 'AY'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Obligor Country', 'obligor_country', 'Obligor Country', 'string', '', 52, true, true, true, 1, 'AZ'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Initial TTM EBITDA', 'initial_ttm_ebitda', 'Initial TTM EBITDA', 'float', '', 53, true, true, true, 1, 'BA'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Debt to Capitalization Ratio', 'debt_to_capitalization_ratio', 'Debt to Capitalization Ratio', 'float', 'percent', 54, true, true, true, 1, 'BB'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Current Moody''s Rating', 'current_moodys_rating', 'Current Moody''s Rating', 'string', '', 55, true, true, true, 1, 'BC'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Current S&P Rating', 'current_sp_rating', 'Current S&P Rating', 'string', '', 56, true, true, true, 1, 'BD'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Eligible Covenant Lite (Y/N)', 'eligible_covenant_lite', 'Eligible Covenant Lite (Y/N)', 'string', '', 57, true, true, true, 1, 'BE'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Credit Improved Loan (Y/N)', 'credit_improved_loan', 'Credit Improved Loan (Y/N)', 'string', '', 58, true, true, true, 1, 'BF'),
 	(2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Equity Security (Y/N)', 'equity_security', 'Equity Security (Y/N)', 'string', '', 59, true, true, true, 1, 'BG'),
    (2, (select smm_id from sheet_metadata_master where lookup = 'loan_list'), 1, 'Maturity Date', 'maturity_date', 'Maturity Date', 'datetime', '', 60, true, true, true, 1, 'BH');
    
    
    
    
    
    
    
    
    