INSERT INTO public.haircut_config (fund_type, company_id, haircut_level, obligor_tier, "position", value, created_by) VALUES
	 ('PFLT', 1, '20% Conc. Limit', 'Tier 1 Obligor', 'SD/EBITDA', 5.0, 1),
	 ('PFLT', 1, '20% Conc. Limit', 'Tier 1 Obligor', 'TD/EBITDA', 7.0, 1),
	 ('PFLT', 1, '20% Conc. Limit', 'Tier 1 Obligor', 'UD/EBITDA', 6.0, 1),
	 ('PFLT', 1, '20% Conc. Limit', 'Tier 2 Obligor', 'SD/EBITDA', 4.25, 1),
	 ('PFLT', 1, '20% Conc. Limit', 'Tier 2 Obligor', 'TD/EBITDA', 6.0, 1),
	 ('PFLT', 1, '20% Conc. Limit', 'Tier 2 Obligor', 'UD/EBITDA', 5.25, 1),
	 ('PFLT', 1, '20% Conc. Limit', 'Tier 3 Obligor', 'SD/EBITDA', 3.75, 1),
	 ('PFLT', 1, '20% Conc. Limit', 'Tier 3 Obligor', 'TD/EBITDA', 5.0, 1),
	 ('PFLT', 1, '20% Conc. Limit', 'Tier 3 Obligor', 'UD/EBITDA', 4.5, 1),
	 ('PFLT', 1, 'Level 1 - 10% Haircut', 'Tier 1 Obligor', 'SD/EBITDA', 5.5, 1),
	 ('PFLT', 1, 'Level 1 - 10% Haircut', 'Tier 1 Obligor', 'TD/EBITDA', 7.5, 1),
	 ('PFLT', 1, 'Level 1 - 10% Haircut', 'Tier 1 Obligor', 'UD/EBITDA', 6.5, 1),
	 ('PFLT', 1, 'Level 1 - 10% Haircut', 'Tier 2 Obligor', 'SD/EBITDA', 4.75, 1),
	 ('PFLT', 1, 'Level 1 - 10% Haircut', 'Tier 2 Obligor', 'TD/EBITDA', 6.5, 1),
	 ('PFLT', 1, 'Level 1 - 10% Haircut', 'Tier 2 Obligor', 'UD/EBITDA', 5.75, 1),
	 ('PFLT', 1, 'Level 1 - 10% Haircut', 'Tier 3 Obligor', 'SD/EBITDA', 4.25, 1);
	 ('PFLT', 1, 'Level 1 - 10% Haircut', 'Tier 3 Obligor', 'TD/EBITDA', 5.5, 1),
	 ('PFLT', 1, 'Level 1 - 10% Haircut', 'Tier 3 Obligor', 'UD/EBITDA', 5.0, 1),
	 ('PFLT', 1, 'Level 2 - 20% Haircut', 'Tier 1 Obligor', 'SD/EBITDA', 6.0, 1),
	 ('PFLT', 1, 'Level 2 - 20% Haircut', 'Tier 1 Obligor', 'TD/EBITDA', 8.0, 1),
	 ('PFLT', 1, 'Level 2 - 20% Haircut', 'Tier 1 Obligor', 'UD/EBITDA', 7.0, 1);
	 ('PFLT', 1, 'Level 2 - 20% Haircut', 'Tier 2 Obligor', 'SD/EBITDA', 5.25, 1),
	 ('PFLT', 1, 'Level 2 - 20% Haircut', 'Tier 2 Obligor', 'TD/EBITDA', 7.0, 1),
	 ('PFLT', 1, 'Level 2 - 20% Haircut', 'Tier 2 Obligor', 'UD/EBITDA', 6.25, 1),
	 ('PFLT', 1, 'Level 2 - 20% Haircut', 'Tier 3 Obligor', 'SD/EBITDA', 4.75, 1),
	 ('PFLT', 1, 'Level 2 - 20% Haircut', 'Tier 3 Obligor', 'TD/EBITDA', 6.0, 1),
	 ('PFLT', 1, 'Level 2 - 20% Haircut', 'Tier 3 Obligor', 'UD/EBITDA', 5.5, 1),
	 ('PFLT', 1, 'Level 3 - 35% Haircut', 'Tier 1 Obligor', 'SD/EBITDA', 6.5, 1),
	 ('PFLT', 1, 'Level 3 - 35% Haircut', 'Tier 1 Obligor', 'TD/EBITDA', 8.5, 1),
	 ('PFLT', 1, 'Level 3 - 35% Haircut', 'Tier 1 Obligor', 'UD/EBITDA', 7.5, 1),
	 ('PFLT', 1, 'Level 3 - 35% Haircut', 'Tier 2 Obligor', 'SD/EBITDA', 5.75, 1),
	 ('PFLT', 1, 'Level 3 - 35% Haircut', 'Tier 2 Obligor', 'TD/EBITDA', 7.5, 1),
	 ('PFLT', 1, 'Level 3 - 35% Haircut', 'Tier 2 Obligor', 'UD/EBITDA', 6.75, 1),
	 ('PFLT', 1, 'Level 3 - 35% Haircut', 'Tier 3 Obligor', 'SD/EBITDA', 5.25, 1),
	 ('PFLT', 1, 'Level 3 - 35% Haircut', 'Tier 3 Obligor', 'TD/EBITDA', 6.5, 1),
	 ('PFLT', 1, 'Level 3 - 35% Haircut', 'Tier 3 Obligor', 'UD/EBITDA', 6.0, 1),
	 ('PFLT', 1, 'Level 4 - Max Eligibility - 50% Haircut', 'Tier 1 Obligor', 'SD/EBITDA', 7.0, 1),
	 ('PFLT', 1, 'Level 4 - Max Eligibility - 50% Haircut', 'Tier 1 Obligor', 'TD/EBITDA', 9.0, 1),
	 ('PFLT', 1, 'Level 4 - Max Eligibility - 50% Haircut', 'Tier 1 Obligor', 'UD/EBITDA', 8.0, 1),
	 ('PFLT', 1, 'Level 4 - Max Eligibility - 50% Haircut', 'Tier 2 Obligor', 'SD/EBITDA', 6.25, 1),
	 ('PFLT', 1, 'Level 4 - Max Eligibility - 50% Haircut', 'Tier 2 Obligor', 'TD/EBITDA', 8.0, 1);
	 ('PFLT', 1, 'Level 4 - Max Eligibility - 50% Haircut', 'Tier 2 Obligor', 'UD/EBITDA', 7.25, 1),
	 ('PFLT', 1, 'Level 4 - Max Eligibility - 50% Haircut', 'Tier 3 Obligor', 'SD/EBITDA', 5.75, 1);
	 ('PFLT', 1, 'Level 4 - Max Eligibility - 50% Haircut', 'Tier 3 Obligor', 'TD/EBITDA', 7.0, 1),
	 ('PFLT', 1, 'Level 4 - Max Eligibility - 50% Haircut', 'Tier 3 Obligor', 'UD/EBITDA', 6.5, 1);
