INSERT INTO public.industry_list (fund_type, company_id, industry_no, industry_name, created_by) VALUES
	 ('PFLT', 1, 1, 'Aerospace & Defense', 1),
	 ('PFLT', 1, 2, 'Air Freight & Logistics', 1),
	 ('PFLT', 1, 3, 'Airlines', 1);
	 ('PFLT', 1, 4, 'Auto Components', 1),
	 ('PFLT', 1, 5, 'Automobiles', 1),
	 ('PFLT', 1, 6, 'Banks', 1),
	 ('PFLT', 1, 7, 'Beverages', 1),
	 ('PFLT', 1, 8, 'Biotechnology', 1),
	 ('PFLT', 1, 9, 'Building Products', 1),
	 ('PFLT', 1, 10, 'Capital Markets', 1),
	 ('PFLT', 1, 11, 'Chemicals', 1),
	 ('PFLT', 1, 12, 'Commercial Services & Supplies', 1),
	 ('PFLT', 1, 13, 'Communications Equipment', 1),
	 ('PFLT', 1, 14, 'Construction & Engineering', 1),
	 ('PFLT', 1, 15, 'Construction Materials', 1),
	 ('PFLT', 1, 16, 'Consumer Finance', 1),
	 ('PFLT', 1, 17, 'Containers & Packaging', 1),
	 ('PFLT', 1, 18, 'Distributors', 1);
	 ('PFLT', 1, 19, 'Diversified Consumer Services', 1),
	 ('PFLT', 1, 20, 'Diversified Financial Services', 1),
	 ('PFLT', 1, 21, 'Diversified Telecommunication Services', 1),
	 ('PFLT', 1, 22, 'Electric Utilities', 1),
	 ('PFLT', 1, 23, 'Electrical Equipment', 1),
	 ('PFLT', 1, 24, 'Electronic Equipment, Instruments & Components', 1),
	 ('PFLT', 1, 25, 'Energy Equipment & Services', 1),
	 ('PFLT', 1, 26, 'Equity Real Estate Investment Trusts (REITs)', 1),
	 ('PFLT', 1, 27, 'Food & Staples Retailing', 1),
	 ('PFLT', 1, 28, 'Food Products', 1),
	 ('PFLT', 1, 29, 'Gas Utilities', 1),
	 ('PFLT', 1, 30, 'Health Care Equipment & Supplies', 1),
	 ('PFLT', 1, 31, 'Health Care Providers & Services', 1),
	 ('PFLT', 1, 32, 'Health Care Technology', 1),
	 ('PFLT', 1, 33, 'Hotels, Restaurants & Leisure', 1),
	 ('PFLT', 1, 34, 'Household Durables', 1),
	 ('PFLT', 1, 35, 'Household Products', 1),
	 ('PFLT', 1, 36, 'Independent Power and Renewable Electricity Producers', 1),
	 ('PFLT', 1, 37, 'Industrial Conglomerates', 1),
	 ('PFLT', 1, 38, 'Insurance', 1),
	 ('PFLT', 1, 39, 'Internet and Catalog Retail', 1),
	 ('PFLT', 1, 40, 'Internet Software & Services', 1),
	 ('PFLT', 1, 41, 'IT Services', 1),
	 ('PFLT', 1, 42, 'Leisure Products', 1),
	 ('PFLT', 1, 43, 'Life Sciences Tools & Services', 1),
	 ('PFLT', 1, 44, 'Machinery', 1),
	 ('PFLT', 1, 45, 'Marine', 1),
	 ('PFLT', 1, 46, 'Media', 1),
	 ('PFLT', 1, 47, 'Metals & Mining', 1),
	 ('PFLT', 1, 48, 'Mortgage Real Estate Investment Trusts (REITs)', 1),
	 ('PFLT', 1, 49, 'Multiline Retail', 1),
	 ('PFLT', 1, 50, 'Multi-Utilities', 1),
	 ('PFLT', 1, 51, 'Oil, Gas & Consumable Fuels', 1),
	 ('PFLT', 1, 52, 'Paper & Forest Products', 1),
	 ('PFLT', 1, 53, 'Personal Products', 1),
	 ('PFLT', 1, 54, 'Pharmaceuticals', 1),
	 ('PFLT', 1, 55, 'Professional Services', 1),
	 ('PFLT', 1, 56, 'Real Estate Management & Development', 1),
	 ('PFLT', 1, 57, 'Road & Rail', 1),
	 ('PFLT', 1, 58, 'Semiconductors & Semiconductor Equipment', 1),
	 ('PFLT', 1, 59, 'Software', 1),
	 ('PFLT', 1, 60, 'Specialty Retail', 1),
	 ('PFLT', 1, 61, 'Technology Hardware, Storage & Peripherals', 1),
	 ('PFLT', 1, 62, 'Textiles, Apparel & Luxury Goods', 1),
	 ('PFLT', 1, 63, 'Thrifts & Mortgage Finance', 1),
	 ('PFLT', 1, 64, 'Tobacco', 1),
	 ('PFLT', 1, 65, 'Trading Companies & Distributors', 1),
	 ('PFLT', 1, 66, 'Transportation Infrastructure', 1),
	 ('PFLT', 1, 67, 'Water Utilities', 1),
	 ('PFLT', 1, 68, 'Wireless Telecommunication Services', 1),