INSERT INTO base_data_mapping (
    fund_type,
    company_id,
    bd_sheet_name,
    bd_column_name,
    bd_column_lookup,
    bd_column_datatype,
    bd_column_unit,
    sf_file_type,
    sf_sheet_name,
    sf_column_name,
    sf_column_lookup,
    sf_column_datatype,
    sf_column_categories
) VALUES 
    ('PSSL', 1, 'Portfolio', 'Initial Gross Senior Debt (Local Currency)', 'initial_gross_senior_debt', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'Senior Debt', 'senior_debt', 'float', ARRAY['IDI$AM']);
    ('PSSL', 1, 'Portfolio', 'Initial Gross Total Debt (Local Currency)', 'initial_gross_total_debt', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'Total Debt', 'total_debt', 'float', ARRAY['IDI$AM']),
    ('PSSL', 1, 'Portfolio', 'Current Unrestricted Cash (Local Currency)', 'current_unrestricted_cash', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'Current Unrestricted Cash', 'current_unrestricted_cash', 'float', ARRAY['CDI$AM']),
    ('PSSL', 1, 'Portfolio', 'Current Gross Senior Debt (Local Currency)', 'current_gross_senior_debt', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'Senior Debt', 'senior_debt', 'float', ARRAY['CDI$AM']),
    ('PSSL', 1, 'Portfolio', 'Current Gross Total Debt (Local Currency)', 'current_gross_total_debt', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'Total Debt', 'total_debt', 'float', ARRAY['CDI$AM']),
    ('PSSL', 1, 'Portfolio', 'Upfront Approval Rights', 'upfront_approval_rights', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Upfront Approval Rights', 'upfront_approval_rights', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Eligible Loan Attestation', 'eligible_loan_attestation', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Eligible Loan', 'eligible_loan', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Cov-Lite', 'cov_lite', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Cov-Lite?', 'cov_lite', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Spread', 'spread', 'float', 'percent', 'master_comp', 'PSSL II Borrowing Base',
        'Spread', 'spread', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'DIP Loan', 'dip_loan', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'DIP Loan', 'dip_loan', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Approved Country', 'approved_country', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Approved Country Domicile', 'approved_country_domicile', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Approved Currency', 'approved_currency', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Approved Currency', 'approved_currency', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Approved Industry', 'approved_industry', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'GICS Industry', 'gics_industry', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Is Fixed Rate', 'is_fixed_rate', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Fixed Rate?', 'fixed_rate?', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Interest Paid (Mthly, Qtrly)', 'interest_paid', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Interest Paid (Mthly, Qtrly)', 'interest_paid', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Paid Less than Qtrly', 'paid_less_than_qtrly', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Paid Less than Qtrly or Mthly', 'paid_less_than_qtrly_or_mthly', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'S&P Rating', 'sp_rating', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'S&P', 'sp', 'string', ARRAY['Rating']),
    ('PSSL', 1, 'Portfolio', 'Moody''s Rating', 'moodys_rating', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Moody''s', 'moodys', 'string', ARRAY['Rating']),
    ('PSSL', 1, 'Portfolio', 'Rated B- or Better', 'rated_b_or_better', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Rated B- or Better', 'rated_b_or_better', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Adjusted TTM EBITDA', 'adjusted_ttm_ebitda', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
    	'Adjusted TTM EBITDA', 'adjusted_ttm_ebitda', 'float', NULL),
    ('PSSL', 1, 'Portfolio', 'Two Market Quotes', 'two_market_quotes', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Two Market Quotes', 'two_market_quotes', 'string', NULL);


INSERT INTO base_data_mapping (
    fund_type,
    company_id,
    bd_sheet_name,
    bd_column_name,
    bd_column_lookup,
    bd_column_datatype,
    bd_column_unit,
    sf_file_type,
    sf_sheet_name,
    sf_column_name,
    sf_column_lookup,
    sf_column_datatype,
    sf_column_categories
) VALUES 
    ('PSSL', 1, 'Portfolio', 'Date of TTM Financials', 'date_of_ttm_financials', 'datetime', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Date of TTM Financials', 'date_of_ttm_financials', 'datetime', '{Initial EBITDA}'),
    ('PSSL', 1, 'Portfolio', 'Initial TTM Adjusted EBITDA', 'initial_ttm_adjusted_ebitda', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'Adjusted TTM EBITDA', 'adjusted_ttm_ebitda', 'float', '{Initial EBITDA}'),
    ('PSSL', 1, 'Portfolio', 'Add-Backs', 'add_backs', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'EBITDA AddBacks', 'ebitda_addbacks', 'float', '{Initial EBITDA}'),
    ('PSSL', 1, 'Portfolio', 'Obligor Payment Default', 'obligor_payment_default', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Obligor Payment Default', 'obligor_payment_default', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Exercise Rights and Remedies', 'exercise_rights_and_remedies', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Exercise of Rights and Remedies', 'exercise_of_rights_and_remedies', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Reduces/Waives Principal', 'reduces_waives_principal', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Reduces/Waives Principal', 'reduces_waives_principal', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Extends Maturity Date', 'extends_maturity_date', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Extends Maturity/Payment Date', 'extends_maturity_payment_date', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Reduces/Waives Interest', 'reduces_waives_interest', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Waives Interest', 'waives_interest', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Subordinates Loan(s)', 'subordinates_loans', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Subordinates Loan', 'subordinates_loan', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Releases Collateral/Lien', 'releases_collateral_lien', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Releases Collateral/Lien', 'releases_collateral_lien', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Amends Covenants', 'amends_covenants', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Amends Covenants', 'amends_covenants', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Reporting Failure Event', 'reporting_failure_event', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Failure to Deliver Financial Reports', 'failure_to_deliver_financial_reports', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Insolvency Event', 'insolvency_event', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Obligor Insolvency Event', 'obligor_insolvency_event', 'string', '{VALUE ADJUSTMENT EVENT}'),
    ('PSSL', 1, 'Portfolio', 'Borrower', 'borrower', 'string', '', 'cashfile', 'US Bank Holdings', 
        'Issuer/Borrower Name', 'issuer_borrower_name', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'Loan Type', 'loan_type', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'Loan Type', 'loan_type', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'RCF Exposure Type', 'rcf_exposure_type', 'string', '', 'master_comp', 'PSSL II Borrowing Base', 
        'RCF Exposure Type', 'rcf_exposure_type', 'string', NULL),
    ('PSSL', 1, 'Portfolio', 'RCF Commitment Amount', 'rcf_commitment_amount', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'RCF Commitment Amount', 'rcf_commitment_amount', 'float', NULL),
    ('PSSL', 1, 'Portfolio', 'Borrower Outstanding Principal Balance', 'borrower_outstanding_principal_balance', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'Borrower Outstanding Principal Balance', 'borrower_outstanding_principal_balance', 'float', NULL),
    ('PSSL', 1, 'Portfolio', 'Borrower Facility Commitment', 'borrower_facility_commitment', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'Borrower Facility Commitment', 'borrower_facility_commitment', 'float', NULL),
    ('PSSL', 1, 'Portfolio', 'Initial Unrestricted Cash (Local Currency)', 'initial_unrestricted_cash', 'float', 'currency', 'master_comp', 'PSSL II Borrowing Base', 
        'Initial Unrestricted Cash', 'initial_unrestricted_cash', 'float', NULL);






INSERT INTO base_data_mapping (
    fund_type,
    company_id,
    bd_sheet_name,
    bd_column_name,
    bd_column_lookup,
    bd_column_datatype,
    bd_column_unit,
    sf_file_type,
    sf_sheet_name,
    sf_column_name,
    sf_column_lookup,
    sf_column_datatype,
    sf_column_categories
) VALUES 
    ('PSSL', 1, 'Portfolio', 'Acquisition Price', 'acquisition_price', 'float', 'percent', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Origination Date', 'origination_date', 'datetime', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Acquisition Date', 'acquisition_date', 'datetime', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Maturity Date', 'maturity_date', 'datetime', '', 'cashfile', 'US Bank Holdings', 
       'Maturity Date', 'maturity_date', 'datetime', NULL),
    ('PSSL', 1, 'Portfolio', 'Revolver', 'revolver', 'string', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'DDTL', 'ddtl', 'string', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Relevent Test Period', 'relevent_test_period', 'datetime', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Initial Annualized Recurring Revenue', 'initial_annualized_recurring_revenue', '', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Annualized Recurring Revenue', 'annualized_recurring_revenue', '', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Initial Liquidity', 'initial_liquidity', '', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Current  Liquidity', 'current_liquidity', '', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Initial Cash Interest Expense', 'initial_cash_interest_expense', 'float', 'currency', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Current  Cash Interest Expense', 'current_cash_interest_expense', 'float', 'currency', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Amends Definitions (Permitted Lien/Indebtedness)', 'amends_definitions', 'string', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Waives or Extends Due Date of Financial Reports', 'waives_or_extends_due_date_of_financial_reports', 'string', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'Finanicals Since Received?', 'finanicals_since_received', 'string', '', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'RCF Outstanding Amount', 'rcf_outstanding_amount', 'float', 'currency', NULL, NULL, 
       NULL, NULL, NULL, NULL),
    ('PSSL', 1, 'Portfolio', 'RCF Update Date', 'rcf_update_date', 'datetime', '', NULL, NULL, 
       NULL, NULL, NULL, NULL);