global:
  currency: 'USD'                                    # ['USD', 'CAD', ...]
  date-format: 'DD-MMM-YYYY'                         # [ 'MM-DD-YYYY', 'YYYY-MM-DD', ...]
  amount-display-style: 'comma-separated'            # ['comma-separated', 'human-readable']
  amount-decimal-places : 0                          # [0, 2] 
  amount-decimal-places-in-human-readable-format : 1 # [0, 1, 2] 

fund_std_col_map:
  Max. Industry Concentration (% BB):
    PCOF: 
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Industry:
        Sheet Name: PL BB Build
        Column Name: Eligible Industry
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Borrowing Base
      Industry:
        Sheet Name: Loan List
        Column Name: Obligor Industry
  Min. Eligible Issuers (#):
    PCOF:
      Eligible Issuer:
        Sheet Name: PL BB Build
        Column Name: Eligible Issuers
    PFLT:
      Eligible Issuer:
        Sheet Name: Loan List
        Column Name: Obligor
  Number of Issuers:
    PCOF:
      Eligible Issuer:
        Sheet Name: PL BB Build
        Column Name: Eligible Issuers
    PFLT:
      Eligible Issuer:
        Sheet Name: Loan List
        Column Name: Obligor
  Second Lien and Split Lien:
    PFLT:
      Second Lien and Split Lien:
        Sheet Name: Loan List
        Column Name: Second Lien and Split Lien
      Values:
        Sheet Name: Borrowing Base
        Column Name: Values
      Terms:
        Sheet Name: Borrowing Base
        Column Name: Terms
  Second Lien:
    PFLT:
      Second Lien:
        Sheet Name: Loan List
        Column Name: Second Lien
      Values:
        Sheet Name: Borrowing Base
        Column Name: Values
      Terms:
        Sheet Name: Borrowing Base
        Column Name: Terms
  DIP Collateral Loans:
    PFLT:
      DIP Collateral Loans:
        Sheet Name: Loan List
        Column Name: DIP Collateral Loans
      Values:
        Sheet Name: Borrowing Base
        Column Name: Values
      Terms:
        Sheet Name: Borrowing Base
        Column Name: Terms
  Max. LTV Transactions:
    PCOF:
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      LTV Transaction:
        Sheet Name: PL BB Build
        Column Name: Classifications LTV Transaction
  Max. Foreign Eligible Portfolio Investments:
    PCOF:
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Approved Foreign Jurisdiction:
        Sheet Name: PL BB Build
        Column Name: Classifications Approved Foreign Jurisdiction
  Max. Warehouse Assets:
    PCOF:
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Warehouse Asset:
        Sheet Name: PL BB Build
        Column Name: Classifications Warehouse Asset
  Max. Contribution to BB with Maturity > 8 years:
    PCOF:
      Maturity Date:
        Sheet Name: PL BB Build
        Column Name: Investment Maturity
      Terms:
        Sheet Name: Availability Borrower
        Column Name: A
      Values:
        Sheet Name: Availability Borrower
        Column Name: B
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
    PFLT:
      Maturity Date:
        Sheet Name: Loan List
        Column Name: Maturity Date
      Terms:
        Sheet Name: Borrowing Base
        Column Name: Terms
      Values:
        Sheet Name: Borrowing Base
        Column Name: Values
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Borrowing Base
  Max. Industry Concentration (Largest Industry, % BB):
    PCOF: 
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Industry:
        Sheet Name: PL BB Build
        Column Name: Eligible Industry
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Borrowing Base
      Industry:
        Sheet Name: Loan List
        Column Name: Obligor Industry
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
  Max. Industry Concentration (2nd Largest Industry, % BB):
    PCOF: 
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Industry:
        Sheet Name: PL BB Build
        Column Name: Eligible Industry
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Borrowing Base
      Industry:
        Sheet Name: Loan List
        Column Name: Obligor Industry
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
  First Lien Three Largest Obligors (each):
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Exess:
        Sheet Name: Portfolio
        Column Name: Top 3 Excess
      Obligor:
        Sheet Name: Portfolio
        Column Name: Borrower
      Loan Type:
        Sheet Name: Portfolio
        Column Name: Loan Type
  Other Obligors:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Excess:
        Sheet Name: Portfolio
        Column Name: Other Excess
      Obligor:
        Sheet Name: Portfolio
        Column Name: Borrower
      Revised Value:
        Sheet Name: Portfolio
        Column Name: First Lien Last Out, Second Lien Loan not in Top Three Obligors Revised Value
  Third Largest Industry:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
      Excess:
        Sheet Name: Portfolio
        Column Name: Third Largest Industry Excess
  Other Industry:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
      Excess:
        Sheet Name: Portfolio
        Column Name: Other Industries Excess
  Largest Industry:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
      Excess:
        Sheet Name: Portfolio
        Column Name: Largest Industry Excess
  Second Largest Industry:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
      Excess:
        Sheet Name: Portfolio
        Column Name: Second Largest Industry Excess
  EBITDA < $10MM:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Other Industries Revised Value
      Permitted TTM EBITDA (USD):
        Sheet Name: Portfolio
        Column Name: Permitted TTM EBITDA (USD) at relevant test period
  DIP Loans:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: EBITDA Less Than $10MM Revised Value
      DIP Loan:
        Sheet Name: Portfolio
        Column Name: DIP Loan
  DDTL and Revolving Loans:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revolver:
        Sheet Name: Portfolio
        Column Name: Revolver
      DDTL:
        Sheet Name: Portfolio
        Column Name: DDTL
      Revised Value:
        Sheet Name: Portfolio
        Column Name: DIP Loans Revised Value
  Pay Less Frequently than Quarterly:
    PSSL:
      Borrowing Base:
          Sheet Name: Portfolio
          Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: DDTL and Revolving Loans Revised Value
      Paid Less than Qtrly:
        Sheet Name: Portfolio
        Column Name: Paid Less than Qtrly
  Loans denominated in Approved Foreign Currency:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Pay Less Frequently than Quarterly Revised Value
      Approved Currency:
        Sheet Name: Portfolio
        Column Name: Approved Currency
  Loans to Obligors domiciled in Approved Foreign Country:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Approved Foreign Currency Revised Value
      Approved Country:
        Sheet Name: Portfolio
        Column Name: Approved Country
  Cov-Lite:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Approved Foreign Country Revised Value
      Cov-Lite:
        Sheet Name: Portfolio
        Column Name: Cov-Lite
      