global:
  currency: 'USD'                                    # ['USD', 'CAD', ...]
  date-format: 'DD-MMM-YYYY'                         # [ 'MM-DD-YYYY', 'YYYY-MM-DD', ...]
  amount-display-style: 'comma-separated'            # ['comma-separated', 'human-readable']
  amount-decimal-places : 0                          # [0, 2] 
  amount-decimal-places-in-human-readable-format : 1 # [0, 1, 2] 

fund_std_col_map:
  Max. Industry Concentration (% BB):
    PCOF: 
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Industry:
        Sheet Name: PL BB Build
        Column Name: Eligible Industry
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Borrowing Base
      Industry:
        Sheet Name: Loan List
        Column Name: Obligor Industry
  Min. Eligible Issuers (#):
    PCOF:
      Eligible Issuer:
        Sheet Name: PL BB Build
        Column Name: Eligible Issuers
    PFLT:
      Eligible Issuer:
        Sheet Name: Loan List
        Column Name: Obligor
  Number of Issuers:
    PCOF:
      Eligible Issuer:
        Sheet Name: PL BB Build
        Column Name: Eligible Issuers
    PFLT:
      Eligible Issuer:
        Sheet Name: Loan List
        Column Name: Obligor
  Second Lien and Split Lien:
    PFLT:
      Second Lien and Split Lien:
        Sheet Name: Loan List
        Column Name: Second Lien and Split Lien
      Values:
        Sheet Name: Borrowing Base
        Column Name: Values
      Terms:
        Sheet Name: Borrowing Base
        Column Name: Terms
  Second Lien:
    PFLT:
      Second Lien:
        Sheet Name: Loan List
        Column Name: Second Lien
      Values:
        Sheet Name: Borrowing Base
        Column Name: Values
      Terms:
        Sheet Name: Borrowing Base
        Column Name: Terms
  DIP Collateral Loans:
    PFLT:
      DIP Collateral Loans:
        Sheet Name: Loan List
        Column Name: DIP Collateral Loans
      Values:
        Sheet Name: Borrowing Base
        Column Name: Values
      Terms:
        Sheet Name: Borrowing Base
        Column Name: Terms
  Max. LTV Transactions:
    PCOF:
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      LTV Transaction:
        Sheet Name: PL BB Build
        Column Name: Classifications LTV Transaction
  Max. Foreign Eligible Portfolio Investments:
    PCOF:
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Approved Foreign Jurisdiction:
        Sheet Name: PL BB Build
        Column Name: Classifications Approved Foreign Jurisdiction
  Max. Warehouse Assets:
    PCOF:
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Warehouse Asset:
        Sheet Name: PL BB Build
        Column Name: Classifications Warehouse Asset
  Max. Contribution to BB with Maturity > 8 years:
    PCOF:
      Maturity Date:
        Sheet Name: PL BB Build
        Column Name: Investment Maturity
      Terms:
        Sheet Name: Availability Borrower
        Column Name: A
      Values:
        Sheet Name: Availability Borrower
        Column Name: B
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
    PFLT:
      Maturity Date:
        Sheet Name: Loan List
        Column Name: Maturity Date
      Terms:
        Sheet Name: Borrowing Base
        Column Name: Terms
      Values:
        Sheet Name: Borrowing Base
        Column Name: Values
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Borrowing Base
  Max. Industry Concentration (Largest Industry, % BB):
    PCOF: 
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Industry:
        Sheet Name: PL BB Build
        Column Name: Eligible Industry
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Borrowing Base
      Industry:
        Sheet Name: Loan List
        Column Name: Obligor Industry
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
  Max. Industry Concentration (2nd Largest Industry, % BB):
    PCOF: 
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Industry:
        Sheet Name: PL BB Build
        Column Name: Eligible Industry
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Borrowing Base
      Industry:
        Sheet Name: Loan List
        Column Name: Obligor Industry
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
  First Lien Three Largest Obligors (each):
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Exess:
        Sheet Name: Portfolio
        Column Name: Top 3 Excess
      Obligor:
        Sheet Name: Portfolio
        Column Name: Borrower
      Loan Type:
        Sheet Name: Portfolio
        Column Name: Loan Type
  Other Obligors:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Excess:
        Sheet Name: Portfolio
        Column Name: Other Excess
      Obligor:
        Sheet Name: Portfolio
        Column Name: Borrower
      Revised Value:
        Sheet Name: Portfolio
        Column Name: First Lien Last Out, Second Lien Loan not in Top Three Obligors Revised Value
  Third Largest Industry:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
      Excess:
        Sheet Name: Portfolio
        Column Name: Third Largest Industry Excess
  Other Industry:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
      Excess:
        Sheet Name: Portfolio
        Column Name: Other Industries Excess
  Largest Industry:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
      Excess:
        Sheet Name: Portfolio
        Column Name: Largest Industry Excess
  Second Largest Industry:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Industry:
        Sheet Name: Portfolio
        Column Name: Approved Industry
      Excess:
        Sheet Name: Portfolio
        Column Name: Second Largest Industry Excess
  EBITDA < $10MM:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Other Industries Revised Value
      Permitted TTM EBITDA (USD):
        Sheet Name: Portfolio
        Column Name: Permitted TTM EBITDA (USD) at relevant test period
  DIP Loans:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: EBITDA Less Than $10MM Revised Value
      DIP Loan:
        Sheet Name: Portfolio
        Column Name: DIP Loan
  DDTL and Revolving Loans:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revolver:
        Sheet Name: Portfolio
        Column Name: Revolver
      DDTL:
        Sheet Name: Portfolio
        Column Name: DDTL
      Revised Value:
        Sheet Name: Portfolio
        Column Name: DIP Loans Revised Value
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Partial PIK Loan Net Loan Balance
      Revolver:
        Sheet Name: Loan List
        Column Name: Revolver
      DDTL:
        Sheet Name: Loan List
        Column Name: DDTL
  Pay Less Frequently than Quarterly:
    PSSL:
      Borrowing Base:
          Sheet Name: Portfolio
          Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: DDTL and Revolving Loans Revised Value
      Paid Less than Qtrly:
        Sheet Name: Portfolio
        Column Name: Paid Less than Qtrly
    PFLT:
      Borrowing Base:
          Sheet Name: Loan List
          Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Credit Improved Loans Net Loan Balance
      Paid Less than Qtrly:
        Sheet Name: Loan List
        Column Name: Paid Less than Qtrly
  Loans denominated in Approved Foreign Currency:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Pay Less Frequently than Quarterly Revised Value
      Approved Currency:
        Sheet Name: Portfolio
        Column Name: Approved Currency
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Fixed Rate Loan Net Loan Balance
      Approved Currency:
        Sheet Name: Loan List
        Column Name: Currency (USD / CAD / AUD / EUR)
  Loans to Obligors domiciled in Approved Foreign Country:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Approved Foreign Currency Revised Value
      Approved Country:
        Sheet Name: Portfolio
        Column Name: Approved Country
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: DIP Collateral Loans Net Loan Balance
      Approved Country:
        Sheet Name: Loan List
        Column Name: Obligor Country
  Cov-Lite:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Approved Foreign Country Revised Value
      Cov-Lite:
        Sheet Name: Portfolio
        Column Name: Cov-Lite
  Tier 3 Obligors (Measured at Inclusion):
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Eligibility Check:
        Sheet Name: Portfolio
        Column Name: Eligibility Check
      Tier:
        Sheet Name: Portfolio
        Column Name: Tier
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Cov-Lite Revised Value
  Second Lien Loans:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Loan Type:
        Sheet Name: Portfolio
        Column Name: Calculated Loan Type post AA Discretion
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Tier 3 Obligors (Measured at Inclusion) Revised Value
  First Lien Last Out:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Loan Type:
        Sheet Name: Portfolio
        Column Name: Calculated Loan Type post AA Discretion
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Second Lien Loans Revised Value
  Loans with Remaining Maturity > 6 Years:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Remaining Term:
        Sheet Name: Portfolio
        Column Name: Remaining Term
      Revised Value:
        Sheet Name: Portfolio
        Column Name: First Lien Last Out Revised Value
  Recurring Revenue Loans:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Loan Type:
        Sheet Name: Portfolio
        Column Name: Calculated Loan Type post AA Discretion
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Loans with Remaining Maturity > 6 Years Revised Value
  Fixed Rate Loans:
    PSSL:
      Borrowing Base:
        Sheet Name: Portfolio
        Column Name: Adjusted Borrowing Value
      Revised Value:
        Sheet Name: Portfolio
        Column Name: Recurring Revenue Loans Revised Value
      Is Fixed Rate:
        Sheet Name: Portfolio
        Column Name: Is Fixed Rate
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Eligible Covenant Lite Loans Net Loan Balance
      Is Fixed Rate:
        Sheet Name: Loan List
        Column Name: Fixed Rate (Y/N)
  Max. Weighted Average Leverage thru Borrower:
    PCOF:
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Leverage:
        Sheet Name: PL BB Build
        Column Name: Leverage PCOF IV Leverage
      Percent Adj. Elig. Amount:
        Sheet Name: PL BB Build
        Column Name: Concentration % Adj. Elig. Amount (excluding cash)
  Min. Cash, First Lien, and Cov-Lite:
    PCOF:
      Investment Type:
        Sheet Name: PL BB Build
        Column Name: Investment Investment Type
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
  Min. Senior Secured:
    PCOF:
      Investment Type:
        Sheet Name: PL BB Build
        Column Name: Investment Investment Type
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
  Min. Weighted Average Cash Fixed Coupon:
    PCOF:
      Weighted Fixed:
        Sheet Name: PL BB Build
        Column Name: Weighted Fixed
      Investment Name:
        Sheet Name: PL BB Build
        Column Name: Investment Name
  Min. Weighted Average Cash Floating Coupon:
    PCOF:
      Weighted Floating:
        Sheet Name: PL BB Build
        Column Name: Weighted Floating
      Investment Name:
        Sheet Name: PL BB Build
        Column Name: Investment Name
  Max. Third Party Finance Companies:
    PCOF:
      LTV Transaction:
        Sheet Name: PL BB Build
        Column Name: Classifications LTV Transaction
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
  Max. Affiliate Investments:
    PCOF:
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Affiliate Investment:
        Sheet Name: PL BB Build
        Column Name: Classifications Affiliate Investment
  Max. PIK, DIP:
    PCOF:
      Adjusted Type:
        Sheet Name: PL BB Build
        Column Name: Classification Adj. Adjusted Type
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
  Max. Issuer Concentration (% BB):
    PCOF:
      Borrowing Base:
        Sheet Name: PL BB Build
        Column Name: Borrowing Base
      Issuer Concentration:
        Sheet Name: PL BB Build
        Column Name: ONW Adjustments Adj. Contr. % (issuer)
  Max. Weighted Average Maturity (Years):
    PCOF:
      Tenor:
        Sheet Name: PL BB Build
        Column Name: Investment Tenor
      Concentration % Adj. Elig. Amount (excluding cash):
        Sheet Name: PL BB Build
        Column Name: Concentration % Adj. Elig. Amount (excluding cash)
  Partial PIK Loan:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Eligible Foreign Country Net Loan Balance
      Partial PIK Loan:
        Sheet Name: Loan List
        Column Name: Partial PIK Loan (Y/N)
  Discount Collateral Loans:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Revolving / Delayed Drawdown Net Loan Balance
      Discount Collateral Loans:
        Sheet Name: Loan List
        Column Name: Discount Collateral Loan (Y/N)
  Credit Improved Loans:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Discount Loans Net Loan Balance
      Credit Improved Loans:
        Sheet Name: Loan List
        Column Name: Credit Improved Loan (Y/N)
  Warrants to Purchase Equity Securities:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Less Than Quarterly Pay Net Loan Balance
      Warrants to Purchase Equity:
        Sheet Name: Loan List
        Column Name: Warrants to Purchase Equity (Y/N)
  LBO Loan:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Warrants to Purchase Equity Securities Net Loan Balance
      LBO Loan:
        Sheet Name: Loan List
        Column Name: LBO Loan (Y/N)
  Participation Interests:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: LBO Loan with Equity to Cap <25% Net Loan Balance
      Participation Interests:
        Sheet Name: Loan List
        Column Name: Parti-cipation (Y/N)
  Eligible Covenant Lite Loans:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Participation Interests Net Loan Balance
      Eligible Covenant Lite Loans:
        Sheet Name: Loan List
        Column Name: Eligible Covenant Lite (Y/N)
  Top 5 Obligors:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Revised Value:
        Sheet Name: Loan List
        Column Name: Obligor Industry FH Net Loan Balance
  LTM EBITDA < 15,000,000:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      LTM EBITDA < 15,000,000:
        Sheet Name: Loan List
        Column Name: LTM EBITDA < 15,000,000
  LTM EBITDA >= 5,000,000 but < 7,500,000:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      LTM EBITDA >= 5,000,000 but < 7,500,000:
        Sheet Name: Loan List
        Column Name: LTM EBITDA >= 5,000,000 but < 7,500,000
  Leverage Limitations:
    PFLT:
      Borrowing Base:
        Sheet Name: Loan List
        Column Name: Concentration Test Balance - OPB + Eligible Unfunded
      Leverage Limitations:
        Sheet Name: Loan List
        Column Name: LTM Snr Debt / EBITDA
      

