create table pcof_indsutries(id SERIAL PRIMARY KEY, industry_name text)
INSERT INTO pcof_indsutries (industry_name) VALUES
('Aerospace & Defense'),
('Auto Sector'),
('Beverage, Food & Tobacco'),
('Broadcasting & Entertainment'),
('Building Materials'),
('Buildings & Real Estate'),
('Business Services'),
('Cable Television'),
('Cargo Transport'),
('Chemicals, Plastics & Rubber'),
('Communications'),
('Containers, Packaging & Glass'),
('Consumer Products'),
('Distribution'),
('Diversified / Conglomerate Manufacturing'),
('Diversified / Conglomerate Services'),
('Diversified Natural Resources, Precious Metals & Minerals'),
('Ecological'),
('Education'),
('Electronics'),
('Energy / Utilities'),
('Environmental Services'),
('Farming & Agriculture'),
('Finance'),
('Financial Services'),
('Food'),
('Grocery'),
('Healthcare, Education & Childcare'),
('Home & Office Furnishings, Housewares & Durable Consumer Products'),
('Homebuilding'),
('Hotel, Motels, Inns & Gaming'),
('Insurance'),
('Leisure, Amusement, Motion Pictures, Entertainment'),
('Lodging, Leisure, Resorts'),
('Machinery (Non-Agriculture, Non-Construction & Non-Electronic)'),
('Manufacturing / Basic Industry'),
('Media'),
('Mining, Steel, Iron & Non-Precious Metals'),
('Oil & Gas'),
('Other Media'),
('Packaging'),
('Personal, Food & Miscellaneous Services'),
('Personal & Non-Durable Consumer Products (Manufacturing Only)'),
('Personal Transportation'),
('Printing & Publishing'),
('Restaurants'),
('Retail'),
('Retail Store'),
('Telecommunications'),
('Textiles & Leather'),
('Transportation'),
('Cash')