CREATE TABLE public.sf_sheet_borrower_stats (
	"Company" text NULL,
	"Newly Added Deal?" text NULL,
	"[F] PNNT" int8 NULL,
	"[F] PFLT" int8 NULL,
	"[F] PCOF II" int8 NULL,
	"[F] PCOF III" int8 NULL,
	"[F] PSCF-Unlev" int8 NULL,
	"[F] PSCF-Lev" int8 NULL,
	"[F] PSSL" int8 NULL,
	"[CM] [CS] Updated as of" timestamp NULL,
	"[CM] [CS] Cash" text NULL,
	"[CM] [CS] Revolver" text NULL,
	"[CM] [CS] Other First Lien" text NULL,
	"[CM] [CS] First Lien Term Loan" text NULL,
	"[CM] [CS] Second Lien" text NULL,
	"[CM] [CS] Senior Notes" text NULL,
	"[CM] [CS] Senior Unsecured Notes" text NULL,
	"[CM] [CS] Senior Unsecured Toggle" text NULL,
	"[CM] [CS] Senior Subordinated Notes" text NULL,
	"[CM] [CS] Other" text NULL,
	"[CM] [CS] HoldCo" text NULL,
	"[CM] [CS] Market Cap / Contributed Equity" text NULL,
	"[CM] [CS] nan" float8 NULL,
	"[CM] [R] LTM Revenue" text NULL,
	"[CM] [R] LTM EBITDA" text NULL,
	"[CM] [R] LTM CapEx" text NULL,
	"[CM] [R] LTM Cash Interest" text NULL,
	"[CM] [R] Run-Rate Cash Interest" text NULL,
	"[CM] [R] Taxes" text NULL,
	"[CM] [R] Management Fees" text NULL,
	"[CM] [R] Amortization" text NULL,
	"[CM] [R] Current Debt to Capitalization Ratio" text NULL,
	"[CM] [FP&P] Current EBITDA Adjustments" text NULL,
	"[CM] [L/Q] PY Rev" text NULL,
	"[CM] [L/Q] CY Rev" text NULL,
	"[CM] [L/Q] PY Adj. EBITDA" text NULL,
	"[CM] [L/Q] CY Adj. EBITDA" text NULL,
	"[CM] [Y] PY Rev" text NULL,
	"[CM] [Y] CY Rev" text NULL,
	"[CM] [Y] PY Adj. EBITDA" text NULL,
	"[CM] [Y] CY Adj. EBITDA" text NULL,
	"[CM] [CLSO] 1st Lien Net Debt / EBITDA" text NULL,
	"[CM] [CLSO] OpCo Net Debt / EBITDA" text NULL,
	"[CM] [CLSO] HoldCo Net Debt / EBITDA" text NULL,
	"[CM] [CLSO] 1st Lien Net Debt / EBITDA - CapEx" text NULL,
	"[CM] [CLSO] Net Debt / EBITDA - CapEx" text NULL,
	"[CM] [CLSO] HoldCo Net Debt / EBITDA - CapEx" text NULL,
	"[CM] [CLSO] EBITDA / Cash Interest" float8 NULL,
	"[CM] [CLSO] EBITDA - CapEx / Cash Interest" text NULL,
	"[CM] [CLSO] Covenant Senior Leverage" text NULL,
	"[CM] [CLSO] Covenant Total Leverage" text NULL,
	"[CM] [CLSO] nan" float8 NULL,
	"[ACM] [COI/LC] Closing Date" timestamp NULL,
	"[ACM] [COI/LC] S&P Industry" text NULL,
	"[ACM] [COI/LC] Moody's Industry" text NULL,
	"[ACM] [COI/LC] PNNT Industry" text NULL,
	"[ACM] [COI/LC] Purchase Price" text NULL,
	"[ACM] [COI/LC] Rating" text NULL,
	"[ACM] [C-ACM(AC] LTM Revenue" text NULL,
	"[ACM] [C-ACM(AC] LTM EBITDA" text NULL,
	"[ACM] [C-ACM(AC] LTM CapEx" text NULL,
	"[ACM] [C-ACM(AC] LTM Cash Interest" text NULL,
	"[ACM] [C-ACM(AC] 1st Lien Net Debt / EBITDA" text NULL,
	"[ACM] [C-ACM(AC] OpCo Net Debt / EBITDA" text NULL,
	"[ACM] [C-ACM(AC] HoldCo Net Debt / EBITDA" text NULL,
	"[ACM] [C-ACM(AC] 1st Lien Net Debt / EBITDA - CapEx" text NULL,
	"[ACM] [C-ACM(AC] Net Debt / EBITDA - CapEx" text NULL,
	"[ACM] [C-ACM(AC] HoldCo Net Debt / EBITDA - CapEx" text NULL,
	"[ACM] [C-ACM(AC] EBITDA / Cash Interest" float8 NULL,
	"[ACM] [C-ACM(AC] EBITDA - CapEx / Cash Interest" float8 NULL,
	"[ACM] [C-ACM(AC] Closing Fixed Charge Coverage Ratio" float8 NULL,
	"[ACM] [C-ACM(AC] Closing Debt to Capitalization" float8 NULL,
	"[ACM] [P] First Lien" text NULL,
	"[ACM] [P] Second Lien" text NULL,
	"[ACM] [P] Senior Notes" text NULL,
	"[ACM] [P] Senior Unsecured Notes" text NULL,
	"[ACM] [P] Senior Unsecured Toggle" text NULL,
	"[ACM] [P] Senior Subordinated Notes" text NULL,
	"[ACM] [P] Other / HoldCo" text NULL,
	"Capitalization Multiple" text NULL,
	"LIBOR / SOFR" text NULL,
	"Deal Team" text NULL,
	"First Lien Debt" text NULL,
	"Second Lien Debt" text NULL,
	"Total Debt" text NULL,
	nan float8 NULL,
	"Headquarters" text NULL,
	source_file_id int8 NULL
);

CREATE TABLE public.sf_sheet_client_holdings (
	"Asset ID" text NULL,
	"Facility ID" int8 NULL,
	"LoanX ID" text NULL,
	"As Of Date" timestamp NULL,
	"Issuer/Borrower Name" text NULL,
	"Issue Name" text NULL,
	"Par Amount (Deal Currency)" text NULL,
	"Principal Balance (Deal Currency)" text NULL,
	"Issuer Industry Classification - Moody's" text NULL,
	"Issuer Industry Classification - S&P" text NULL,
	"Credit Opinion" text NULL,
	"Credit Opinion Date" timestamp NULL,
	"Maturity Date" timestamp NULL,
	"PIK - PIKable" int8 NULL,
	"Coupon Type Desc" text NULL,
	"Coupon Index Type Desc" text NULL,
	"Current Coupon" text NULL,
	"Effective Spread" float8 NULL,
	"Current Spread" text NULL,
	"Facility Libor Floor" text NULL,
	"Payment Period" text NULL,
	"Recovery Rate - Fitch 6" float8 NULL,
	"Recovery Rate - Fitch 7" float8 NULL,
	"Recovery Rate - Fitch 8" int8 NULL,
	"Recovery Rate - Fitch 9" int8 NULL,
	"Recovery Rate - S&P" int8 NULL,
	"Country" text NULL,
	"Moody's Priority Category" text NULL,
	"Deal Issue (Derived) Rating - Moody's" text NULL,
	"Deal Issue (Derived) Rating - S&P" text NULL,
	"Facility Number" text NULL,
	"Exchange rate" int8 NULL,
	"Current Par Amount (Issue Currency) - Settled" text NULL,
	"Current Par Amount (Issue Currency) - Traded" text NULL,
	source_file_id int8 NULL
);

CREATE TABLE public.sf_sheet_pflt_borrowing_base (
	nan text NULL,
	"Security" text NULL,
	"Issuer" text NULL,
	"Credit Facility Lien Type" text NULL,
	"Credit Facility Loan Type" text NULL,
	"Stretch Senior (Y/N)" text NULL,
	"S&P Industry" text NULL,
	"Currency" text NULL,
	"Obligor Country" text NULL,
	"Corporate Rating" text NULL,
	"Closing Fixed Charge Coverage Ratio" text NULL,
	"Closing Debt to Capitalization Ratio" float8 NULL,
	"Closing Senior Leverage" text NULL,
	"Closing Total Leverage" text NULL,
	"Closing LTM EBITDA" text NULL,
	"Current LTM EBITDA" text NULL,
	"Current Senior Leverage" float8 NULL,
	"Current Total Leverage" float8 NULL,
	"Current Debt to Capitalization Ratio" text NULL,
	"Current Information as of Date" timestamp NULL,
	nan_1 float8 NULL,
	"Convertible into Equity" int8 NULL,
	"Equity Security" int8 NULL,
	"Subject of an Offer or Called for Redemption" int8 NULL,
	"Margin Stock" int8 NULL,
	"Subject to Withholding Tax" int8 NULL,
	"Defaulted Collateral Loan at Acquisition" int8 NULL,
	"All PIK" int8 NULL,
	"Zero Coupon Obligation" int8 NULL,
	"Covenant Lite" int8 NULL,
	"Eligible Covie Lite (1L, Issue > $250mm, B3 / B-)" int8 NULL,
	"Structured Finance Obligation / finance lease" int8 NULL,
	"Material Non-Credit Related Risk" int8 NULL,
	"Primarily Secured by Real Estate" int8 NULL,
	"Interest Only Security" int8 NULL,
	"Satisfies Other Criteria(1)" int8 NULL,
	nan_2 float8 NULL,
	"DIP Loans" int8 NULL,
	"Partial PIK Loan" int8 NULL,
	"Obligations w/ Warrants attached" int8 NULL,
	"Equity < 25% for LBO Loan" int8 NULL,
	"Participations" int8 NULL,
	nan_3 float8 NULL,
	"Defaulted Loan" int8 NULL,
	"Credit Improved Loan" int8 NULL,
	nan_4 float8 NULL,
	"Cash" text NULL,
	"Senior Debt" text NULL,
	"Net Senior Debt" text NULL,
	"Total Debt" text NULL,
	"Net Total Debt" text NULL,
	"LTM EBITDA" text NULL,
	"Sr. Leverage" float8 NULL,
	"Total Leverage" float8 NULL,
	nan_5 float8 NULL,
	"PF Debt" float8 NULL,
	"Q2'19 EBITDA" text NULL,
	"Q2 / LTM Decline %" text NULL,
	"Q2'20E EBITDA" text NULL,
	"LTM Decline $" text NULL,
	"Comments" text NULL,
	"Projected 6/30 LTM EBITDA" text NULL,
	"Projected Senior Leverage" text NULL,
	"Projected Total Leverage" text NULL,
	"Defaulted Loan_1" int8 NULL,
	"Material Modification" int8 NULL,
	"Partial PIK (at least L + 450 cash)" int8 NULL,
	"All PIK_1" int8 NULL,
	"Ineligible Cov-Lite" int8 NULL,
	nan_6 float8 NULL,
	"Projected 7/31/2020 LTM EBITDA" text NULL,
	"Projected Senior Leverage_1" text NULL,
	"Projected Total Leverage_1" text NULL,
	"Defaulted Loan_2" text NULL,
	"Material Modification_1" text NULL,
	"Partial PIK (at least L + 450 cash)_1" text NULL,
	"All PIK_2" text NULL,
	"Ineligible Cov-Lite_1" text NULL,
	nan_7 float8 NULL,
	"Projected 8/31/2020 LTM EBITDA" text NULL,
	"Projected Senior Leverage_2" text NULL,
	"Projected Total Leverage_2" float8 NULL,
	"Defaulted Loan_3" int8 NULL,
	"Material Modification_2" int8 NULL,
	"Partial PIK (at least L + 450 cash)_2" int8 NULL,
	"All PIK_3" int8 NULL,
	"Ineligible Cov-Lite_2" int8 NULL,
	nan_8 float8 NULL,
	"Projected 9/30/2020 LTM EBITDA" text NULL,
	"Projected Senior Leverage_3" text NULL,
	"Projected Total Leverage_3" float8 NULL,
	"Defaulted Loan_4" int8 NULL,
	"Material Modification_3" int8 NULL,
	"Partial PIK (at least L + 450 cash)_3" int8 NULL,
	"All PIK_4" int8 NULL,
	"Ineligible Cov-Lite_3" int8 NULL,
	nan_9 float8 NULL,
	"Projected 10/31/2020 LTM EBITDA" text NULL,
	"Projected Senior Leverage_4" text NULL,
	"Projected Total Leverage_4" float8 NULL,
	"Defaulted Loan_5" int8 NULL,
	"Material Modification_4" int8 NULL,
	"Partial PIK (at least L + 450 cash)_4" int8 NULL,
	"All PIK_5" int8 NULL,
	"Ineligible Cov-Lite_4" int8 NULL,
	nan_10 float8 NULL,
	"Projected 11/30/2020 LTM EBITDA" text NULL,
	"Projected Senior Leverage_5" text NULL,
	"Projected Total Leverage_5" float8 NULL,
	"Defaulted Loan_6" int8 NULL,
	"Material Modification_5" int8 NULL,
	"Partial PIK (at least L + 450 cash)_5" int8 NULL,
	"All PIK_6" int8 NULL,
	"Ineligible Cov-Lite_5" int8 NULL,
	nan_11 float8 NULL,
	"Projected 12/31/2020 LTM EBITDA" text NULL,
	"Projected Senior Leverage_6" text NULL,
	"Projected Total Leverage_6" float8 NULL,
	"Defaulted Loan_7" int8 NULL,
	"Material Modification_6" int8 NULL,
	"Partial PIK (at least L + 450 cash)_6" int8 NULL,
	"All PIK_7" int8 NULL,
	"Ineligible Cov-Lite_6" int8 NULL,
	nan_12 float8 NULL,
	"Projected 3/31/2021 LTM EBITDA" text NULL,
	"Projected Senior Leverage_7" text NULL,
	"Projected Total Leverage_7" float8 NULL,
	"Defaulted Loan_8" int8 NULL,
	"Material Modification_7" int8 NULL,
	"Partial PIK (at least L + 450 cash)_7" int8 NULL,
	"All PIK_8" int8 NULL,
	"Ineligible Cov-Lite_7" int8 NULL,
	nan_13 float8 NULL,
	"Projected 6/30/2021 LTM EBITDA" text NULL,
	"Projected Senior Leverage_8" text NULL,
	"Projected Total Leverage_8" float8 NULL,
	"Defaulted Loan_9" int8 NULL,
	"Material Modification_8" int8 NULL,
	"Partial PIK (at least L + 450 cash)_8" int8 NULL,
	"All PIK_9" int8 NULL,
	"Ineligible Cov-Lite_8" int8 NULL,
	source_file_id int8 NULL
);

CREATE TABLE public.sf_sheet_securities_stats (
	"Security" text NULL,
	"Family Name" text NULL,
	"Sponsor" text NULL,
	"[B] Lead Bank / Agent" text NULL,
	"[B] Other Bank 1" text NULL,
	"[B] Other Bank 2" text NULL,
	"[B] Other Bank 3" text NULL,
	"[B] Other Bank 4" text NULL,
	"[B] Cov-Lite?" text NULL,
	"# Lenders" text NULL,
	"[SI] Security Name" text NULL,
	"[SI] Security Type" text NULL,
	"[SI] Credit Facility Lien Type" text NULL,
	"[SI] Credit Facility Loan Type" text NULL,
	"[SI] Stretch Senior (Y/N)" text NULL,
	"[SI] Investment Dates" text NULL,
	"[SI] Broker / Dealer Quoted" text NULL,
	"[SI] Type of Rate" text NULL,
	"[SI] Maturity" text NULL,
	"[SI] LIBOR Floor" text NULL,
	"[SI] Cash Spread to LIBOR" text NULL,
	"[SI] PIK Coupon" text NULL,
	"[SI] Call Protection" text NULL,
	"[SI] First Call Date" text NULL,
	"[SI] Issue Size" text NULL,
	"[SI] Security Rating" text NULL,
	"[SI] Currency" text NULL,
	"[SI] Obligor Country" text NULL,
	"[SI] Pennant Par Value" text NULL,
	"[SI] Blended Purchase Price" text NULL,
	nan text NULL,
	"[PSM] BB Classification" text NULL,
	"[PSM] Priority Revolver?" text NULL,
	"[PSM] Revolver Size" text NULL,
	"[PSM] TEV" text NULL,
	"[PSM] LTV Loan?" text NULL,
	"[PSM] LTV" text NULL,
	"[PSM] Capitalization Multiple" text NULL,
	"[PSM] Defaulted / Restructured?" text NULL,
	nan_1 text NULL,
	"Cash" text NULL,
	"First Lien Debt" text NULL,
	"Second Lien Debt" text NULL,
	"Total Debt" text NULL,
	"EBITDA" text NULL,
	"Security Type" text NULL,
	nan_2 text NULL,
	"First Lien Gross Leverage" text NULL,
	"Second Lien Gross Leverage" text NULL,
	"Total Gross Leverage" text NULL,
	"Pennant Gross Leverage" text NULL,
	"First Lien Net Leverage" text NULL,
	"Second Lien Net Leverage" text NULL,
	"Total Net Leverage" text NULL,
	"Pennant Net Leverage" text NULL,
	nan_3 text NULL,
	nan_4 text NULL,
	"Deal Team" text NULL,
	nan_5 text NULL,
	"TEV Calculation" text NULL,
	"Unnamed1" text NULL,
	"Unnamed2" text NULL,
	"Unnamed3" text NULL,
	"Unnamed4" text NULL,
	"Unnamed5" text NULL,
	"Unnamed6" text NULL,
	"Unnamed7" text NULL,
	"Unnamed8" text NULL,
	"Unnamed9" text NULL,
	"Unnamed10" text NULL,
	"Unnamed11" text NULL,
	nan_6 text NULL,
	"LTV" text NULL,
	"Don't delete — need for COVID analysis" text NULL,
	"Unnamed12" text NULL,
	"[C] LTM Rev" text NULL,
	"[C] LTM EBITDA" text NULL,
	"[C] Cash" text NULL,
	"[C] Funded Revolver" text NULL,
	"[C] LTM Int. Expense" text NULL,
	"[C] Run-rate Int. Expense" text NULL,
	"[AC] LTM Rev" text NULL,
	"[AC] LTM EBITDA" text NULL,
	"[AC] Unnamed13" text NULL,
	"[AC] Unnamed14" text NULL,
	"[AC] Unnamed15" text NULL,
	"[AC] Unnamed16" text NULL,
	"[AC] LTM CapEx" text NULL,
	"[AC] LTM Cash Taxes" text NULL,
	"[AC] LTM Mgmt. Fee" text NULL,
	"[AC] LTM Amort." text NULL,
	"[L/Q] PY Rev" text NULL,
	"[L/Q] CY Rev" text NULL,
	"[L/Q] PY Adj. EBITDA" text NULL,
	"[L/Q] CY Adj. EBITDA" text NULL,
	"[Y] PY Rev" text NULL,
	"[Y] CY Rev" text NULL,
	"[Y] PY Adj. EBITDA" text NULL,
	"[Y] CY Adj. EBITDA" text NULL,
	source_file_id int8 NULL
);

CREATE TABLE public.sf_sheet_us_bank_holdings (
	"CUSIP" text NULL,
	"Security ID" text NULL,
	"LoanX ID" text NULL,
	"Security/Facility Name" text NULL,
	"Issue Name" text NULL,
	"Issuer/Borrower Name" text NULL,
	"Issue Type" text NULL,
	"Facility - Form of Purchase" text NULL,
	"Asset Type4 Desc" text NULL,
	"Facility Category Desc" text NULL,
	"Currency" text NULL,
	"P. Lot Current Par Amount (Deal Currency)" text NULL,
	"Current Par Amount (Issue Currency) - Settled" text NULL,
	"Current Par Amount (Issue Currency) - Traded" text NULL,
	"Unfunded Commitment" int8 NULL,
	"PIK Loan" int8 NULL,
	"Market Value Indenture" float8 NULL,
	"Credit Opinion Date" timestamp NULL,
	"Credit Opinion" text NULL,
	"Maturity Date" timestamp NULL,
	"Original Purchase Price" text NULL,
	"Purchase Date" timestamp NULL,
	"Settle Date" timestamp NULL,
	"Bloomberg ID" text NULL,
	"Issuer ID" int8 NULL,
	"Facility ID" int8 NULL,
	"Issue ID" int8 NULL,
	"ISIN" text NULL,
	"Purchase Lot ID" int8 NULL,
	"Entity ID" int8 NULL,
	"Trustee Deal ID" text NULL,
	"Deal Name" text NULL,
	"Deal Nickname" text NULL,
	source_file_id int8 NULL
);

CREATE TABLE public.sf_sheet_pcof_iii_borrrowing_base (
	nan float8 NULL,
	"Family Name" text NULL,
	"Security Name" text NULL,
	"Investment Type" text NULL,
	"S&P Industry" text NULL,
	"Floating Cash Spread" text NULL,
	"Floor" text NULL,
	"Quoted / Unquoted" text NULL,
	"Approved Foreign Jurisdiction" text NULL,
	"LTV Transaction" text NULL,
	"Noteless Assigned Loan" text NULL,
	"Undelivered Note" text NULL,
	"Structured Finance Obligation" text NULL,
	"Third Party Finance Company" text NULL,
	"Affiliate Investment" text NULL,
	"Defaulted / Restructured" text NULL,
	"LTM Revenue" text NULL,
	"LTM EBITDA" text NULL,
	"Priority Revolver Det" int8 NULL,
	"TEV" text NULL,
	"Total Gross Leverage" text NULL,
	"Total PCOF III Leverage" text NULL,
	"TotalCapitalization" text NULL,
	"LTV Deal" text NULL,
	"Warehouse Yes / No" text NULL,
	"Warehouse - Credit Rating" text NULL,
	source_file_id int8 NULL
);

CREATE TABLE public.sf_sheet_pcof_iv (
	nan float8 NULL,
	"Asset" text NULL,
	"MC Name" text NULL,
	"LTM Revenue" float8 NULL,
	"LTM EBITDA" text NULL,
	"Revolver" text NULL,
	"TEV" text NULL,
	"Total Lev" float8 NULL,
	"PCOF IV Lev" float8 NULL,
	"LTV" float8 NULL,
	nan_1 float8 NULL,
	nan_2 float8 NULL,
	nan_3 text NULL,
	nan_4 float8 NULL,
	nan_5 float8 NULL,
	nan_6 float8 NULL,
	source_file_id int8 NULL
);

create table sf_sheet_soi_mapping (
	"SOI Name" text NULL,
	"Security Name" text NULL,
	"Family Name" text NULL,
	"Security Type" text NULL,
	source_file_id int8 NULL
);

CREATE TABLE public.sf_sheet_marketbook (
	nan text NULL,
	"Issuer" text NULL,
	nan_1 float8 NULL,
	"Asset" text NULL,
	"(NC)" text NULL,
	nan_2 float8 NULL,
	"Committed" text NULL,
	"Book Value" text NULL,
	"Market Value" text NULL,
	nan_3 float8 NULL,
	"MV Price" text NULL,
	"Book Value_1" text NULL,
	"BV Price" text NULL,
	"MV - BV" text NULL,
	source_file_id int8 NULL
);



CREATE TABLE public.sf_sheet_pssl_ii_borrowing_base (
	"[IDI$AM] Initial Unrestricted Cash" float8 NULL,
	"[IDI$AM] Initial Total Debt" float8 NULL,
	"[CDI$AM] Current Unrestricted Cash" float8 NULL,
	"[CDI$AM] Current Senior Debt" float8 NULL,
	"[CDI$AM] Current Total Debt" float8 NULL,
	"Upfront Approval Rights" varchar NULL,
	"Eligible Loan" varchar NULL,
	"Cov-Lite?" varchar NULL,
	spread float8 NULL,
	"DIP Loan" varchar NULL,
	"Approved Country Domicile" varchar NULL,
	"Approved Currency" varchar NULL,
	"GICS Industry" varchar NULL,
	"Fixed Rate?" varchar NULL,
	"Interest Paid (Mthly, Qtrly)" varchar NULL,
	"Paid Less than Qtrly or Mthly" varchar NULL,
	"[R] S&P" varchar NULL,
	"[R] Moody's" varchar NULL,
	"Rated B- or better" varchar NULL,
	"Two Market  Quotes" varchar NULL,
	"[IE] Initial Date of TTM Financials" varchar NULL,
	"[IE] Initial Adjusted TTM EBITDA" float8 NULL,
	"[IE] Initial Initial EBITDA Addbacks" float8 NULL,
	"[VAE] Obligor Payment Default" varchar NULL,
	"[VAE] Exercise of Rights and Remedies" varchar NULL,
	"[VAE] (a) Reduces/waives Principal" varchar NULL,
	"[VAE] (b) Extends Maturity/ Payment Date" varchar NULL,
	"[VAE] (c) Waives Interest" varchar NULL,
	"[VAE] (d) Subordinates Loan" varchar NULL,
	"[VAE] (e) Releases Collateral/Lien" varchar NULL,
	"[VAE] (f) Amends Covenants" varchar NULL,
	"[VAE] (f) Failure to Deliver Financial Reports" varchar NULL,
	"[VAE] (e) Obligor Insolvency Event" varchar NULL,
	"Loan Type" varchar NULL,
	"RCF Exposure Type" varchar NULL,
	"RCF Commitment Amount" float8 NULL,
	"Borrower Outstanding Principal Balance" varchar NULL,
	"Borrower Facility Commitment" varchar NULL,
	source_file_id int4 NULL,
	"Security" varchar NULL,
	"[IDI$AM] Initial Senior Debt" float8 NULL,
	"[CU] Current Date of TTM Financials" varchar NULL,
	"[CU] Current Adjusted TTM EBITDA" float8 NULL,
	"[CU] Current Current EBITDA Addbacks" varchar NULL
);

CREATE TABLE public.sf_sheet_master_ratings (
	"[BN] Master Comps" varchar NULL,
	"[RD(] [M] Rating" varchar NULL,
	"[RD(] [S] Rating" varchar NULL,
	nan varchar NULL,
	"[RD(] [M] Rating Type" varchar NULL,
	"[RD(] nan" varchar NULL,
	"[RD(] [S] Rating Type" varchar NULL,
	"[RD(] [S] Recovery Rating" varchar NULL,
	"[RD(] [S] Recovery %" varchar NULL,
	"[RD(] nan_1" varchar NULL,
	"[RD(] [F] Rating" varchar NULL,
	"[RD(] [F] Rating Type" varchar NULL,
	"[RD(] nan_2" varchar NULL,
	"[RD(] [DE] S&P" varchar NULL,
	"[RD(] [DE] Fitch" varchar NULL,
	source_file_id int8 NULL,
);