"""empty message

Revision ID: 15254e06559d
Revises: 
Create Date: 2025-01-20 16:00:38.052619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15254e06559d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('pflt_haircut_config',
    sa.Column('hc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_type', sa.String(length=15), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('haircut_level', sa.String(length=127), nullable=False),
    sa.Column('obligor_tier', sa.String(length=127), nullable=False),
    sa.Column('position', sa.String(length=127), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('hc_id')
    )
    op.create_table('pflt_industry_list',
    sa.Column('il_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_type', sa.String(length=15), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('industry_no', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(length=255), nullable=False),
    sa.Column('industry_code', sa.String(length=127), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('il_id')
    )
    op.create_table('extracted_base_data_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fund_type', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('files', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('extraction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('failure_comments', sa.String(), nullable=True),
    sa.Column('user_comments', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pflt_base_data_mapping',
    sa.Column('bdm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_type', sa.String(length=15), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('bd_sheet_name', sa.String(length=255), nullable=False),
    sa.Column('bd_column_name', sa.String(length=255), nullable=False),
    sa.Column('bd_column_lookup', sa.String(length=255), nullable=True),
    sa.Column('bd_column_datatype', sa.String(length=255), nullable=True),
    sa.Column('bd_column_is_required', sa.Boolean(), nullable=True),
    sa.Column('bd_column_unit', sa.String(), nullable=True),
    sa.Column('sf_file_type', sa.String(length=255), nullable=True),
    sa.Column('sf_sheet_name', sa.String(length=255), nullable=True),
    sa.Column('sf_column_name', sa.String(), nullable=True),
    sa.Column('sf_column_lookup', sa.String(length=255), nullable=True),
    sa.Column('sf_column_datatype', sa.String(length=255), nullable=True),
    sa.Column('sf_column_categories', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sd_ref_table_name', sa.String(), nullable=True),
    sa.Column('formula', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('bdm_id')
    )
    op.create_table('pflt_security_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('soi_name', sa.String(), nullable=True),
    sa.Column('master_comp_security_name', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('security_type', sa.String(), nullable=True),
    sa.Column('cashfile_security_name', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pflt_base_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_data_info_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('obligor_name', sa.String(), nullable=True),
    sa.Column('security_name', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.String(), nullable=True),
    sa.Column('total_commitment', sa.String(), nullable=True),
    sa.Column('outstanding_principal', sa.String(), nullable=True),
    sa.Column('defaulted_collateral_loan', sa.String(), nullable=True),
    sa.Column('credit_improved_loan', sa.String(), nullable=True),
    sa.Column('purchase_price', sa.String(), nullable=True),
    sa.Column('stretch_senior_loan', sa.String(), nullable=True),
    sa.Column('loan_type', sa.String(), nullable=True),
    sa.Column('current_moodys_rating', sa.String(), nullable=True),
    sa.Column('current_sp_rating', sa.String(), nullable=True),
    sa.Column('initial_fixed_charge_coverage_ratio', sa.String(), nullable=True),
    sa.Column('date_of_default', sa.String(), nullable=True),
    sa.Column('market_value', sa.String(), nullable=True),
    sa.Column('current_fixed_charge_coverage_ratio', sa.String(), nullable=True),
    sa.Column('current_interest_coverage_ratio', sa.String(), nullable=True),
    sa.Column('initial_interest_coverage_ratio', sa.String(), nullable=True),
    sa.Column('initial_debt_to_capitalization_ratio', sa.String(), nullable=True),
    sa.Column('initial_senior_debt_ebitda', sa.String(), nullable=True),
    sa.Column('initial_total_debt_ebitda', sa.String(), nullable=True),
    sa.Column('current_senior_debt_ebitda', sa.String(), nullable=True),
    sa.Column('current_total_debt_ebitda', sa.String(), nullable=True),
    sa.Column('initial_ttm_ebitda', sa.String(), nullable=True),
    sa.Column('current_ttm_ebitda', sa.String(), nullable=True),
    sa.Column('current_as_of_date', sa.String(), nullable=True),
    sa.Column('maturity_date', sa.String(), nullable=True),
    sa.Column('fixed_rate', sa.String(), nullable=True),
    sa.Column('coupon_incl_pik_pikable', sa.String(), nullable=True),
    sa.Column('floor_obligation', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('spread_incl_pik_pikable', sa.String(), nullable=True),
    sa.Column('base_rate', sa.String(), nullable=True),
    sa.Column('for_unused_fee', sa.String(), nullable=True),
    sa.Column('pik_pikable_for_floating_rate_loans', sa.String(), nullable=True),
    sa.Column('pik_pikable_for_fixed_rate_loans', sa.String(), nullable=True),
    sa.Column('interest_paid', sa.String(), nullable=True),
    sa.Column('obligor_industry', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('obligor_country', sa.String(), nullable=True),
    sa.Column('dip_loan', sa.String(), nullable=True),
    sa.Column('lbo_loan', sa.String(), nullable=True),
    sa.Column('warrants_to_purchase_equity', sa.String(), nullable=True),
    sa.Column('participation', sa.String(), nullable=True),
    sa.Column('convertible_to_equity', sa.String(), nullable=True),
    sa.Column('equity_security', sa.String(), nullable=True),
    sa.Column('at_acquisition_offer_or_redemption', sa.String(), nullable=True),
    sa.Column('margin_stock', sa.String(), nullable=True),
    sa.Column('subject_to_withholding_tax', sa.String(), nullable=True),
    sa.Column('at_acquisition_defaulted_loan', sa.String(), nullable=True),
    sa.Column('zero_coupon_obligation', sa.String(), nullable=True),
    sa.Column('covenant_lite', sa.String(), nullable=True),
    sa.Column('eligible_covenant_lite', sa.String(), nullable=True),
    sa.Column('lien_type', sa.String(), nullable=True),
    sa.Column('structured_finance_obligation', sa.String(), nullable=True),
    sa.Column('material_non_credit_related_risk', sa.String(), nullable=True),
    sa.Column('primarily_secured_by_real_estate_or_loan', sa.String(), nullable=True),
    sa.Column('minimum_equity_amount_floor', sa.String(), nullable=True),
    sa.Column('interest_only_security', sa.String(), nullable=True),
    sa.Column('satisfies_all_other_eligibility_criteria', sa.String(), nullable=True),
    sa.Column('excess_concentration_amount', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['base_data_info_id'], ['extracted_base_data_info.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_archvied', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.drop_column('is_archvied')
        batch_op.drop_column('report_date')

    op.drop_table('pflt_base_data')
    op.drop_table('users')
    op.drop_table('pflt_security_mapping')
    op.drop_table('pflt_base_data_mapping')
    op.drop_table('extracted_base_data_info')
    op.drop_table('pflt_industry_list')
    op.drop_table('pflt_haircut_config')
    op.drop_table('companies')
    # ### end Alembic commands ###
