"""empty message

Revision ID: 339b83fdc492
Revises: 
Create Date: 2025-01-13 12:16:53.092591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '339b83fdc492'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_base_data_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failure_comments', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_comments', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_column('comments')

    with op.batch_alter_table('pflt_base_data_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sd_ref_table_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('formula', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=True))

    with op.batch_alter_table('pflt_security_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('soi_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('master_comp_security_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('family_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('security_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('cashfile_security_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['company_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('pflt_security_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('cashfile_security_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('security_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('family_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('master_comp_security_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('soi_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('created_by')

    with op.batch_alter_table('pflt_base_data_mapping', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('description')
        batch_op.drop_column('formula')
        batch_op.drop_column('sd_ref_table_name')

    with op.batch_alter_table('extracted_base_data_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('description')
        batch_op.drop_column('user_comments')
        batch_op.drop_column('failure_comments')

    # ### end Alembic commands ###
