"""Added column report_date in SourceFiles

Revision ID: 57a2f1f536d2
Revises: d6142cf28148
Create Date: 2024-12-18 14:36:46.989423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a2f1f536d2'
down_revision = 'd6142cf28148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.drop_column('report_date')

    # ### end Alembic commands ###
