"""empty message

Revision ID: 9b547a8e9151
Revises: 15254e06559d
Create Date: 2025-01-21 16:31:47.058261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b547a8e9151'
down_revision = '15254e06559d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pflt_base_data', schema=None) as batch_op:
        batch_op.drop_column('minimum_equity_amount_floor')

    with op.batch_alter_table('pflt_base_data_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_editable', sa.Boolean(), server_default=sa.text('false'), nullable=True))

    with op.batch_alter_table('pflt_haircut_config', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('pflt_industry_list', schema=None) as batch_op:
        batch_op.alter_column('industry_code',
               existing_type=sa.VARCHAR(length=127),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_types', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.drop_column('fund_type')
        batch_op.drop_column('is_archvied')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archvied', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fund_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('is_archived')
        batch_op.drop_column('fund_types')

    with op.batch_alter_table('pflt_industry_list', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('industry_code',
               existing_type=sa.VARCHAR(length=127),
               nullable=False)

    with op.batch_alter_table('pflt_haircut_config', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('pflt_base_data_mapping', schema=None) as batch_op:
        batch_op.drop_column('is_editable')

    with op.batch_alter_table('pflt_base_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_equity_amount_floor', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
