"""empty message

Revision ID: b32ff481eac4
Revises: 
Create Date: 2024-11-18 17:32:29.409986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32ff481eac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concentration_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ct_code', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=15), server_default='percentage', nullable=True))
        batch_op.add_column(sa.Column('data_type', sa.String(length=15), server_default='integer', nullable=True))
        batch_op.add_column(sa.Column('default_value', sa.Integer(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('eligible_funds', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(None, ['ct_code'])

    with op.batch_alter_table('fund_concentration_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund_concentration_test', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('concentration_test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('eligible_funds')
        batch_op.drop_column('default_value')
        batch_op.drop_column('data_type')
        batch_op.drop_column('unit')
        batch_op.drop_column('ct_code')

    # ### end Alembic commands ###
