"""empty message

Revision ID: ca68f48321f8
Revises: 18ff42a23ddf
Create Date: 2025-02-13 18:23:43.870486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca68f48321f8'
down_revision = '18ff42a23ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pcof_base_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_eligible_issuer', sa.String(), nullable=True))

    with op.batch_alter_table('pcof_base_data_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_eligible_issuer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pcof_base_data_history', schema=None) as batch_op:
        batch_op.drop_column('is_eligible_issuer')

    with op.batch_alter_table('pcof_base_data', schema=None) as batch_op:
        batch_op.drop_column('is_eligible_issuer')

    # ### end Alembic commands ###
