"""added column file_type in SourceFiles

Revision ID: d6142cf28148
Revises: b32ff481eac4
Create Date: 2024-12-17 11:52:54.595559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6142cf28148'
down_revision = 'b32ff481eac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
